### ISSUE TITLE
Specifying multiple input types for one query parameter triggers "KeyError"

### ISSUE THREAD

**Issue by lzy7071** [zalando/connexion#1069]
### Description
Specifying multiple input types for one query parameter triggers "KeyError", relevant spec is as follows (with proper indentation):
    parameters:
      - in: query
        name: species
        schema:
          oneOf:
            - type: string
            - type: integer
        required: true

### Expected behaviour
When parameter "species" is of either string instance or integer instance, the request will return expected results.

### Actual behaviour
The following error message was displayed, I am not sure if this is a connexion issue or Flask issue:
ERROR    test_taxon:app.py:1891 Exception on /taxon/canon_rank_distance/ [GET]
Traceback (most recent call last):
  File "/home/zl/.conda/envs/py36/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/zl/.conda/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/zl/.conda/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/zl/.conda/envs/py36/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/zl/.conda/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/zl/.conda/envs/py36/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/zl/.conda/envs/py36/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/home/zl/.conda/envs/py36/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 170, in wrapper
    request.query = self.resolve_query(query)
  File "/home/zl/.conda/envs/py36/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 210, in resolve_query
    return self.resolve_params(query_data, 'query')
  File "/home/zl/.conda/envs/py36/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 127, in resolve_params
    if (param_schema is not None and param_schema['type'] == 'array'):
KeyError: 'type'

Output of the commands:

- `python --version`: Python 3.6.9 :: Anaconda, Inc.
- `pip show connexion | grep "^Version\:"` Version: 2.4.0

**Comment by dtkav** [comment]
Can you post a complete openapi schema please? (and make sure it's valid).
Off the top of my head, I don't think specifying multiple types like that is valid. If it were, which one should connexion use to case the type?

**Comment by dtkav** [comment]
I'm closing this for now. If you'd still like help, please reopen and provide a minimal reproducible example.

**Comment by germannp** [comment]
We are running into the same issue, here is a small reproducible example:

```python
import connexion

def post_greeting(name):
    return f'Hello {name}'

if __name__ == '__main__':
    app = connexion.FlaskApp(__name__, port=9090, specification_dir='./')
    app.add_api('helloworld-api.yaml')
    app.run()
```

And the API definition would be

```yaml
openapi: "3.0.0"

info:
  title: Hello World
  version: "1.0"

paths:
  /greeting/{name}:
    get:
      summary: Generate greeting
      description: Generates a greeting message.
      operationId: hello.post_greeting
      responses:
        200:
          description: greeting response
          content:
            text/plain:
              schema:
                type: string
                example: "hello dave!"
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          schema:
            oneOf:
              - type: string
              - type: integer
            example: "dave"
```
which is valid, according to `openapi-spec-validator`.

Without `connexion` this could be achieved with

```python
from flask import Flask
from waitress import serve

app = Flask(__name__)

@app.route("/greeting/<string:name>")
def greet_person(name):
    return f'Hello {name}'

@app.route("/greeting/<int:number>")
def greet_number(number):
    return f'Hello #{number}'

serve(app, listen="*:8005")
```
... but I don't know, whether that makes sense with `connexion` :-)

**Comment by killerpanda101** [comment]
Hi, I am facing the same issue as @germannp is there a fix or workaround available?

**Comment by huogerac** [comment]
I needed to add two entries in the openapi.yml as workaround, one for the type: string and another for the type: integer. It has a little bit of DRY in the YAML, but works very well, and in the backend/service layer I have no duplication. In another word, I can call my api using '/greeting/abc' and '/greeting/100', first will call the backend passing string and second as integer.

When I tried to use the oneOf passing both types, it runs, shows the API documentation (swagger), however, when I try to call the API, I get the following error:

```
  File "/home/roger/.ve/tenmaisapi/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/roger/.ve/tenmaisapi/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/roger/.ve/tenmaisapi/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roger/.ve/tenmaisapi/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roger/.ve/tenmaisapi/lib/python3.8/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/home/roger/.ve/tenmaisapi/lib/python3.8/site-packages/connexion/decorators/security.py", line 327, in wrapper
    return function(request)
  File "/home/roger/.ve/tenmaisapi/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 142, in wrapper
    request.path_params = self.resolve_path(path_params)
  File "/home/roger/.ve/tenmaisapi/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 218, in resolve_path
    return self.resolve_params(path_data, 'path')
  File "/home/roger/.ve/tenmaisapi/lib/python3.8/site-packages/connexion/decorators/uri_parsing.py", line 111, in resolve_params
    if (param_schema is not None and param_schema['type'] == 'array'):
KeyError: 'type'
```

my virtualenv:
```
Python 3.8.9
Flask==1.1.2
connexion==2.7.0
openapi-schema-validator==0.1.5
openapi-spec-validator==0.3.0
PyYAML==5.4.1
swagger-ui-bundle==0.0.8
```

I hope this could be further information for someone who wants to improve the connexion or for someone that needs to use as it is today.
Cheers

**Comment by huogerac** [comment]
> I'm closing this for now. If you'd still like help, please reopen and provide a minimal reproducible example.



> Can you post a complete openapi schema please? (and make sure it's valid).
> Off the top of my head, I don't think specifying multiple types like that is valid. If it were, which one should connexion use to case the type?

I believe that the specification supports multiple types:
Please, check the 'Mixed Types' in the link below.
https://swagger.io/docs/specification/data-models/data-types/
