### ISSUE TITLE
x-tokenInfoFunc security decorator overrides @injected function arguments

### ISSUE THREAD

**Issue by AviranAbady** [zalando/connexion#1144]
### Description
When setting a validation function using `x-tokenInfoFunc`

```
securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: http://127.0.0.1:8080//login
    x-tokenInfoFunc: api.auth.validate_token
    scopes:
      user: Unique identifier of the user accessing the service.
      basic: A credential supporting fetching of all user's data
```
In case `validate_token` is defined as follows:

```
@inject
def validate_token(access_token, injectedArg: InjectedType):
    ...
    ...
```
I'm using `FlaskInjector`
in the following way:
```
def configure(binder):
    ...
    ...

FlaskInjector(app=app.app, modules=[configure])
```

### Expected behaviour
`validate_token()` should be invoked with the access_token and the injectedArg
(Works fine with endpoint functions referenced by operationId)

### Actual behaviour
`verify_token` is called with a single argument (token), which will raise the following exception:
```
Traceback (most recent call last):
  File "venv3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "venv3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "venv3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "venv3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "venv3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "venv3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "venv3/lib/python3.7/site-packages/flask_injector.py", line 89, in wrapper
    return injector.call_with_injection(callable=fun, args=args, kwargs=kwargs)
  File "venv3/lib/python3.7/site-packages/injector/__init__.py", line 980, in call_with_injection
    reraise(e, CallError(self_, callable, args, dependencies, e, self._stack))
  File "venv3/lib/python3.7/site-packages/injector/__init__.py", line 196, in reraise
    raise exception.with_traceback(tb)
  File "venv3/lib/python3.7/site-packages/injector/__init__.py", line 978, in call_with_injection
    return callable(*full_args, **dependencies)
  File "venv3/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "venv3/lib/python3.7/site-packages/connexion/decorators/security.py", line 311, in wrapper
    token_info = get_authorization_info(auth_funcs, request, required_scopes)
  File "venv3/lib/python3.7/site-packages/connexion/decorators/security.py", line 127, in get_authorization_info
    token_info = func(request, required_scopes)
  File "venv3/lib/python3.7/site-packages/connexion/decorators/security.py", line 188, in wrapper
    token_info = verify_authorization_token(request, token_info_func)
  File "/venv3/lib/python3.7/site-packages/connexion/decorators/security.py", line 175, in verify_authorization_token
    token_info = token_info_func(token)
TypeError: validate_token() missing 1 required positional argument: 'injectedArg'
```

### Additional info:
```
$ python --version
Python 3.7.5
$ pip show connexion | grep "^Version\:"
Version: 2.5.1
```

**Comment by sarusiziv** [comment]
I'm also experiencing the same issue, setting a validation function using `x-tokenInfoFunc` which is decorated with @inject and has injected parameters. `security.py` is invoking the validate function with a single parameter and somehow along the way the necessary variables are not injected.

**Comment by pavel-rezabek** [comment]
@AviranAbady
I temporarily solved it by setting the FlaskInjector object to the flask app under connexion:

```python
app = connexion.App(__name__)
def configure(binder):
    ...
    ...

injector = FlaskInjector(app=app.app, modules=[configure])
app.app.injector = injector
```

Then you can access this object from within the `x-tokenInfoFunc` using flask's `current_app`:
```python
from flask import current_app

def validate_token(access_token):
    injectedArg = current_app.injector.injector.get(InjectedType)
    # Do whatever
```

It is a hacky way, but it made my app work.

**Comment by AviranAbady** [comment]
@RobbeSneyders Why did you close the issue? Is there a solution to the issue?

**Comment by RobbeSneyders** [comment]
Hi @AviranAbady.
`x-tokenInfoFunc` is not  called by Flask, but by connexion directly. As far as I understand, it's never configured by `FlaskInjector` beacause of this.

If you want to inject the request context, you can use connexion's own injection mechanism for this by using the [`pass_context_arg_name`](https://connexion.readthedocs.io/en/latest/autoapi/connexion/apps/abstract/index.html#connexion.apps.abstract.AbstractApp.add_api) parameter when adding an API.

**Comment by AviranAbady** [comment]
Thanks @RobbeSneyders, I will look into [pass_context_arg_name](https://connexion.readthedocs.io/en/latest/autoapi/connexion/apps/abstract/index.html#connexion.apps.abstract.AbstractApp.add_api). I do believe that using `FlaskInjector` is a more robust approach, when I'll find the time I'll PR a fix to the issue with `get_authorization_info()` in the case of `x-tokenInfoFunc`.
