### ISSUE TITLE
route file per entity fail compile.

### ISSUE THREAD

**Issue by jimsproject** [zalando/connexion#115]
i have swagger yaml that operation id group per entity.  for example i have acc_manager file contain add,update,get,delete function. and so for others like brand, user.
the issue is when i import the library in main script like sqlalchemy.  i have declare db connection in main. then in file acc_manager from myapp import db. when i compile it fail . with err. all function in acc_manager not detect. but if i remove the import line . it is working.  so could you give some example how to manage the route in multiple file . and how to use it with db.

thank you

jimmy

**Comment by hjacobs** [comment]
Can you provide some example code snippets to reproduce the problem?

**Comment by hjacobs** [comment]
I guess the issue is similar to #101

**Comment by jimsproject** [comment]
here the error 
Failed to add operation for POST /v1/am
Traceback (most recent call last):
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 136, in add_paths
    self.add_operation(method, path, endpoint)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 117, in add_operation
    validate_responses=self.validate_responses, resolver=self.resolver)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/operation.py", line 85, in __init__
    resolution = resolver.resolve(self)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 50, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 71, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 87, in get_function_from_name
    function = deep_getattr(module, attr_path)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 69, in deep_getattr
    return functools.reduce(getattr, attr.split('.'), obj)
AttributeError: 'module' object has no attribute 'account_manager'
Failed to add operation for DELETE /v1/am
Traceback (most recent call last):
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 136, in add_paths
    self.add_operation(method, path, endpoint)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 117, in add_operation
    validate_responses=self.validate_responses, resolver=self.resolver)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/operation.py", line 85, in __init__
    resolution = resolver.resolve(self)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 50, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 71, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 87, in get_function_from_name
    function = deep_getattr(module, attr_path)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 69, in deep_getattr
    return functools.reduce(getattr, attr.split('.'), obj)
AttributeError: 'module' object has no attribute 'account_manager'
Failed to add operation for GET /v1/am
Traceback (most recent call last):
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 136, in add_paths
    self.add_operation(method, path, endpoint)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 117, in add_operation
    validate_responses=self.validate_responses, resolver=self.resolver)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/operation.py", line 85, in __init__
    resolution = resolver.resolve(self)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 50, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 71, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 87, in get_function_from_name
    function = deep_getattr(module, attr_path)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 69, in deep_getattr
    return functools.reduce(getattr, attr.split('.'), obj)
AttributeError: 'module' object has no attribute 'account_manager'
Failed to add operation for PUT /v1/am
Traceback (most recent call last):
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 136, in add_paths
    self.add_operation(method, path, endpoint)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 117, in add_operation
    validate_responses=self.validate_responses, resolver=self.resolver)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/operation.py", line 85, in __init__
    resolution = resolver.resolve(self)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 50, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 71, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 87, in get_function_from_name
    function = deep_getattr(module, attr_path)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 69, in deep_getattr
    return functools.reduce(getattr, attr.split('.'), obj)
AttributeError: 'module' object has no attribute 'account_manager'
/home/jimmy/api/lib/python3.4/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
 * Restarting with stat
Failed to add operation for DELETE /v1/am
Traceback (most recent call last):
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 136, in add_paths
    self.add_operation(method, path, endpoint)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 117, in add_operation
    validate_responses=self.validate_responses, resolver=self.resolver)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/operation.py", line 85, in __init__
    resolution = resolver.resolve(self)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 50, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 71, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 87, in get_function_from_name
    function = deep_getattr(module, attr_path)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 69, in deep_getattr
    return functools.reduce(getattr, attr.split('.'), obj)
AttributeError: 'module' object has no attribute 'account_manager'
Failed to add operation for POST /v1/am
Traceback (most recent call last):
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 136, in add_paths
    self.add_operation(method, path, endpoint)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 117, in add_operation
    validate_responses=self.validate_responses, resolver=self.resolver)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/operation.py", line 85, in __init__
    resolution = resolver.resolve(self)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 50, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 71, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 87, in get_function_from_name
    function = deep_getattr(module, attr_path)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 69, in deep_getattr
    return functools.reduce(getattr, attr.split('.'), obj)
AttributeError: 'module' object has no attribute 'account_manager'
Failed to add operation for PUT /v1/am
Traceback (most recent call last):
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 136, in add_paths
    self.add_operation(method, path, endpoint)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 117, in add_operation
    validate_responses=self.validate_responses, resolver=self.resolver)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/operation.py", line 85, in __init__
    resolution = resolver.resolve(self)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 50, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 71, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 87, in get_function_from_name
    function = deep_getattr(module, attr_path)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 69, in deep_getattr
    return functools.reduce(getattr, attr.split('.'), obj)
AttributeError: 'module' object has no attribute 'account_manager'
Failed to add operation for GET /v1/am
Traceback (most recent call last):
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 136, in add_paths
    self.add_operation(method, path, endpoint)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/api.py", line 117, in add_operation
    validate_responses=self.validate_responses, resolver=self.resolver)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/operation.py", line 85, in __init__
    resolution = resolver.resolve(self)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 50, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/resolver.py", line 71, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 87, in get_function_from_name
    function = deep_getattr(module, attr_path)
  File "/home/jimmy/api/lib/python3.4/site-packages/connexion/utils.py", line 69, in deep_getattr
    return functools.reduce(getattr, attr.split('.'), obj)
AttributeError: 'module' object has no attribute 'account_manager'
/home/jimmy/api/lib/python3.4/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
 * Debugger is active!
 * Debugger pin code: 340-151-335
[demo.zip](https://github.com/zalando/connexion/files/68420/demo.zip)

**Comment by hjacobs** [comment]
What Python version are you using? Can you try renaming the `api` package to something else? I suspect the relative imports in Python 2 (?) to import `connexion.api` instead of your `api` module.

**Comment by hjacobs** [comment]
OK, I found the problem: the `account_manager` module cannot import the `db` module as it is defined in `__init__.py`. You have a circular reference (`__init__.py` referencing swagger.yaml and loading the modules which in turn try to load `db` from `__init__.py`.

Try to defer the application initialization or `app.add_api(..)`.
