### ISSUE TITLE
Basic working example for RestyResolver?

### ISSUE THREAD

**Issue by dfeinzeig** [zalando/connexion#120]
I'm trying to get RestyResolver working and I'm encountering an exception:

```
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    app.add_api('swagger.yaml', resolver=RestyResolver('api'))
  File "/local/lib/python2.7/site-packages/connexion/app.py", line 124, in add_api
    self.app.register_blueprint(api.blueprint)
  File "/local/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/local/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/local/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/local/lib/python2.7/site-packages/flask/blueprints.py", line 172, in <lambda>
    s.add_url_rule(rule, endpoint, view_func, **options))
  File "/local/lib/python2.7/site-packages/flask/blueprints.py", line 76, in add_url_rule
    view_func, defaults=defaults, **options)
  File "/local/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/local/lib/python2.7/site-packages/flask/app.py", line 984, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: /v1.api_mypath_get
```

I've defined get() inside of api/mypath.py, which I thought was the right thing to do, omitting operationIDs from my swagger.yaml.

Is there an example that uses RestyResolver?

**Comment by hjacobs** [comment]
Would the exception be fixed with #121?

I haven't used RestyResolver myself yet...

**Comment by hjacobs** [comment]
@kleijnweb as you introduced `RestyResolver`, could you provide some examples (e.g. below https://github.com/zalando/connexion/tree/master/examples/)?

**Comment by kleijnweb** [comment]
Sure. Not before the weekend I'm afraid though.

**Comment by hjacobs** [comment]
:+1: thanks

**Comment by kleijnweb** [comment]
Didn't get around to it yet, but I'll make time coming week or at worst the week after that. I'm going to need it for an upcoming microservice anyway, so it shouldn't be much trouble. Sorry for the delay / poor expectation management.

**Comment by kleijnweb** [comment]
Created the example, tried the Swagger UI, works nicely.

**Comment by hjacobs** [comment]
@dfeinzeig the example is here: https://github.com/zalando/connexion/tree/master/examples/restyresolver
