### ISSUE TITLE
Issue with Boolean type query parameters when using pythonic_params=true.

### ISSUE THREAD

**Issue by ss1895** [zalando/connexion#1307]
### Description
First off, thanks a lot for connexion!

So we have a simple API spec with a query parameter of type **boolean** called **truthiness**. When we pass `truthiness=true` or `truthiness=false` in the URL, all works well. But, if we were to instead pass **Truthiness**(capital T, instead of truthiness), like `Truthiness=true` or `Truthiness=false`, while the expectation is that the parameter is ignored altogether, connexion raises an exception while trying to extract the value of the query parameter. We don't face this issue for query parameters of type string.

Similarly, we don't face this issue if `pythonic_params=false`, but unfortunately, that's not an option for us since we follow camelCasing for names in our API spec design.

OAS 3.0 Spec: **test.yaml**
```
openapi: 3.0.1
info:
  title: Boolean Test
  version: "0"
servers:
- url: /
paths:
  /test:
    get:
      description: A test endpoint.
      parameters:
      - name: truthiness
        in: query
        description: A test parameter.
        schema:
          type: boolean
          default: false
      responses:
        204:
          description: Do some magic.
```

Using **openapi-generator** to generate Python Flask server:
`java -jar openapi-generator-cli.jar generate -i test.yaml -g python-flask -o src_gen`

Simple web server app: **main.py**
```
import sys
sys.path.append("./src_gen")
sys.path.append("./src")
import connexion
from gevent.pywsgi import WSGIServer

app = connexion.App(__name__, specification_dir='../src_gen/openapi_server/openapi/')
app.add_api('openapi.yaml',
  arguments={'title': 'Test API'},
  pythonic_params=True,
)

if __name__ == "__main__":
    server = WSGIServer(('0.0.0.0', 8080), app.app)
    server.serve_forever()
```

When I cURL: `curl -X GET -i "http://localhost:8080/test?Truthiness=false"`
I end up with this exception:
```
[2020-10-17 15:50:50,518] ERROR in app: Exception on /test [GET]
Traceback (most recent call last):
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/connexion/decorators/uri_parsing.py", line 144, in wrapper
    response = function(request)
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/connexion/decorators/validation.py", line 384, in wrapper
    return function(request)
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/connexion/decorators/parameter.py", line 103, in wrapper
    request.files, arguments, has_kwargs, sanitize)
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/connexion/operations/abstract.py", line 268, in get_arguments
    has_kwargs, sanitize))
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/connexion/operations/openapi.py", line 369, in _get_query_arguments
    arguments, has_kwargs, sanitize)
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/connexion/operations/abstract.py", line 200, in _query_args_helper
    res.update({key: self._get_val_from_param(value, query_defn)})
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/connexion/operations/openapi.py", line 380, in _get_val_from_param
    return make_type(value, query_schema["type"])
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/connexion/utils.py", line 40, in make_type
    return type_func(value)
  File "/home/projects/connexion-boolean-bug/venv/lib/python3.6/site-packages/connexion/utils.py", line 20, in boolean
    raise ValueError('Invalid boolean value')
ValueError: Invalid boolean value
```

### Expected behaviour
When `curl -X GET -i "http://localhost:8080/test?Truthiness=false` is executed, Truthiness is simply ignored.

### Actual behaviour
Exception raised by connexion, as mentioned above.

### Steps to reproduce
1) Generate Python-Flask server from spec: `java -jar openapi-generator-cli.jar generate -i test.yaml -g python-flask -o src_gen`
2) Run app: `python src/main.py`
3) cURL: `curl -X GET -i "http://localhost:8080/test?Truthiness=false`. Observe exception raised.

### Additional info:

Output of the commands:

- `python --version`: Python 3.6.9
- `pip show connexion | grep "^Version\:"`: Version: 2.7.0

Thanks a lot for looking into this, in advance! Do let me know in case any more information is required from my side.

**Comment by Ruwann** [comment]
Thanks for the detailed report! I've looked into it a bit and the reason for the `Invalid boolean value` error is because the value that is attempted to be converted is actually a list (`['false']` in this example).

The underlying issue is that for resolving the URI and query parameters, connexion tries to rely on the spec (line 104-105):
https://github.com/zalando/connexion/blob/803cf638785223b3a9321c4ad5bbe371a61e38b6/connexion/decorators/uri_parsing.py#L96-L122

However, the `pythonic_params` conversion from `Truthiness` to `truthiness` only happens at a later stage. So `Truthiness` is not found in the spec.
When using `truthiness` in the curl command, connexion is able to use the spec to determine it is not an array, but a boolean and takes the last value of the array:
https://github.com/zalando/connexion/blob/803cf638785223b3a9321c4ad5bbe371a61e38b6/connexion/decorators/uri_parsing.py#L122

**Comment by Ruwann** [comment]
The underlying issue is https://github.com/zalando/connexion/issues/1183
