### ISSUE TITLE
Missing query parameters returns HTTP 500 instead of 400

### ISSUE THREAD

**Issue by jvgutierrez** [zalando/connexion#131]
swagger endpoint definition:
```
  /dummy:
    get:
      operationId: controllers.dummy.dummy
      parameters:
        - in: query
          name: test
          type: string
          required: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              data:
                type: string
```

Steps to reproduce the issue:

1. Launch app server
2. curl -I http://192.168.99.101:8080/v1/dummy --> returns HTTP 400 as expected
3. curl -I http://192.168.99.101:8080/v1/dummy?test=1 --> returns HTTP 200 as expected
4. curl -I http://192.168.99.101:8080/v1/dummy --> **returns HTTP 500**

stack trace:
```
test_1 | Traceback (most recent call last):
test_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
test_1 |     response = self.full_dispatch_request()
test_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
test_1 |     rv = self.handle_user_exception(e)
test_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
test_1 |     reraise(exc_type, exc_value, tb)
test_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
test_1 |     rv = self.dispatch_request()
test_1 |   File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
test_1 |     return self.view_functions[rule.endpoint](**req.view_args)
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/decorators/validation.py", line 190, in wrapper
test_1 |     response = function(*args, **kwargs)
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/decorators/produces.py", line 116, in wrapper
test_1 |     data, status_code, headers = self.get_full_response(function(*args, **kwargs))
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/decorators/parameter.py", line 100, in wrapper
test_1 |     return function(*args, **kwargs)
test_1 | TypeError: dummy() takes exactly 1 argument (0 given)
```

**Comment by hjacobs** [comment]
Hmm, your points 2 and 4 have the same URL, but return different status codes? How can this be?

Could you also post your Python code?

Thanks!

**Comment by jvgutierrez** [comment]
@hjacobs it changes from 400 to 500 after one request with the mandatory parameter being present.
The code is pretty simple:
```
def dummy(test):
    return {'testa': test}
```

**Comment by hjacobs** [comment]
True, I can confirm the bug.

**Comment by rafaelcaricio** [comment]
@jvgutierrez which version of `connexion` are you using?

**Comment by hjacobs** [comment]
@rafaelcaricio I can reproduce the bug with connexion==1.0.49

**Comment by jvgutierrez** [comment]
@rafaelcaricio I just pushed a test against in my repo https://github.com/jvgutierrez/connexion/commit/7eba65459ad3c1bb03b7663c74df28365bc9b86f.

Check:

```
______________________________________________________________________________ test_missing_params_bug ______________________________________________________________________________

app = <connexion.app.App instance at 0x7fdda2b06c20>

    def test_missing_params_bug(app):
        app_client = app.app.test_client()
        resp = app_client.get('/v1.0/test-missing-params-bug')
        assert resp.status_code == 400
        resp = app_client.get('/v1.0/test-missing-params-bug', query_string={'p': 'test'})
        assert resp.status_code == 200
        resp = app_client.get('/v1.0/test-missing-params-bug')
>       assert resp.status_code == 400
E       assert 500 == 400
E        +  where 500 = <Response streamed [500 INTERNAL SERVER ERROR]>.status_code
```

**Comment by rafaelcaricio** [comment]
@jvgutierrez  I am sending a PR now with the fix. ;)

**Comment by jvgutierrez** [comment]
@rafaelcaricio awesome, thanks :)

**Comment by hjacobs** [comment]
fix released in https://github.com/zalando/connexion/releases/tag/1.0.52
