### ISSUE TITLE
OpenAPI array of objects passed in query causes exception

### ISSUE THREAD

**Issue by colford** [zalando/connexion#1316]
### Description
OpenAPI spec states that you can have an array of objects and that these can be passed in a get query as a parameter, see https://swagger.io/docs/specification/data-models/data-types/. When passing the array of objects OpenAPI uses square bracket notation with duplicate ids. This causes an exception in the uri_parsing.py module within the _resolve_param_duplicates method. 

### Expected behaviour
For the given query request:
```
/v1.0/exploded-deep-object-array-param?ids[foo]=bar&ids[fooint]=1001&ids[fooboo]=true&ids[foo4]=HoHoHo
```
I'd expect something like:
```
{ids: [{foo: 'bar', fooint: 1001, fooboo: True, foo4: 'HoHoHo'}]}
```
...and for the given query request:
```
/v1.0/exploded-deep-object-array-param?foo[p1]=0.0&foo[p2]=-1.1&foo[p1]=2.2&foo[p2]=-3.3&foo[p1]=4.4&foo[p2]=-5.5
```
I'd expect something like:
```
{foo: [{p1: 0.0, p2: -1.1}, {p1: 2.2, p2: -3.3}, {p1: 4.4, p2: -5.5}]}
```
...or...
```
{foo: {p1: [0.0, 2.2, 4.4], p2: [-1.1, -3.3, -5.5]}}
```

### Actual behaviour
An exception is thrown:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/uri_parsing.py", line 141, in wrapper
    request.query = self.resolve_query(query)
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/uri_parsing.py", line 227, in resolve_query
    return self.resolve_params(query_data, 'query')
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/uri_parsing.py", line 113, in resolve_params
    values = self._resolve_param_duplicates(values, param_defn, _in)
  File "/usr/local/lib/python3.6/dist-packages/connexion/decorators/uri_parsing.py", line 247, in _resolve_param_duplicates
    return delimiter.join(values)
TypeError: sequence item 0: expected str instance, dict found
```

### Steps to reproduce
Add to the tests\fixtures\simple\openapi.yaml schema:
```YAML
  /exploded-deep-object-array-param:
    get:
      summary: Returns dict response
      description: Returns dict response
      operationId: fakeapi.hello.test_exploded_deep_object_array_param
      parameters:
        - name: ids
          required: true
          in: query
          style: deepObject
          explode: true
          schema:
            type: array
            items:
              type: object
              additionalProperties: false
              properties:
                foo:
                  type: string
                fooint:
                  type: integer
                fooboo:
                  type: boolean
                foo4:
                  type: string
                  default: blubb
      responses:
        '200':
          description: object response
          content:
            application/json:
              schema:
                type: object
                properties:
                  foo:
                    type: string
                  foo4:
                    type: string
```
Add to the tests\api\test_responses.py
```PYTHON
def test_exploded_deep_object_array_param_endpoint_openapi_simple(simple_openapi_app):
    app_client = simple_openapi_app.app.test_client()

    response = app_client.get('/v1.0/exploded-deep-object-array-param?ids[foo]=bar&ids[fooint]=1001&ids[fooboo]=true&ids[foo4]=HoHoHo')  # type: flask.Response
    assert response.status_code == 200
    response_data = json.loads(response.data.decode('utf-8', 'replace'))
    assert response_data == {'foo': 'bar', 'fooint': 1001, 'fooboo': True, 'foo4': 'HoHoHo'}
```
Add to the tests\fakeapi\hello\__init__.py
```PYTHON
def test_exploded_deep_object_array_param(id):
    return id
```
Run tox and it will fail on the test.
...or just create any valid OpenAPI YAML that creates an array of objects for a query.

### Additional info:

- `python --version`
```
Python 3.6.12
```
- `pip show connexion | grep "^Version\:"`
```
Version: 2.7.0
```
...also occurs with the latest from github.

**Comment by RobbeSneyders** [comment]
Thanks for the report @colford.
Can confirm that I'm able to reproduce this.

**Comment by Kausshalk78** [comment]
Any update on this issue? I am also running into the same problem where we are not able to send an array of objects in query parameter.

**Comment by RobbeSneyders** [comment]
Looking back at this, I don't think OpenAPI supports nested arrays / objects in the query string ([docs](https://swagger.io/docs/specification/serialization/)). Feel free to reopen if you can show that it is supported.
