### ISSUE TITLE
What is the way to declare an endpoint that returns a flask.Response object?

### ISSUE THREAD

**Issue by jvgutierrez** [zalando/connexion#133]
I'm trying to create an endpoint that returns a flask.Response (302).
Code:
```
from flask import redirect
def dummy():
    return redirect('/')
```
But I get the following error:
```
<Response 209 bytes [302 FOUND]> is not JSON serializable
```
Additionally if I try to avoid the JSON conversion setting the output for that endpoint as text/plain using the following swagger definition:
```
  /dummy:
    get:
      produces: "text/plain"
      operationId: controllers.dummy.dummy
      responses:
        302:
          description: OK
```
I get the following stack trace when I launch the server:
```
test_1 | ERROR:connexion.api:Failed to add operation for GET /v1/dummy
test_1 | Traceback (most recent call last):
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/api.py", line 136, in add_paths
test_1 |     self.add_operation(method, path, endpoint)
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/api.py", line 122, in add_operation
test_1 |     self.blueprint.add_url_rule(flask_path, operation.endpoint_name, operation.function, methods=[method])
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/operation.py", line 234, in function
test_1 |     produces_decorator = self.__content_type_decorator
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/operation.py", line 271, in __content_type_decorator
test_1 |     mimetype = self.get_mimetype()
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/operation.py", line 165, in get_mimetype
test_1 |     if produces_json(self.produces):  # endpoint will return json
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/utils.py", line 121, in produces_json
test_1 |     return all(is_json_mimetype(mimetype) for mimetype in produces)
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/utils.py", line 121, in <genexpr>
test_1 |     return all(is_json_mimetype(mimetype) for mimetype in produces)
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/utils.py", line 95, in is_json_mimetype
test_1 |     maintype, subtype = mimetype.split('/')  # type: str, str
test_1 | ValueError: need more than 1 value to unpack
test_1 | ERROR:connexion.api:Failed to add operation for GET /v1/dummy
test_1 | Traceback (most recent call last):
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/api.py", line 136, in add_paths
test_1 |     self.add_operation(method, path, endpoint)
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/api.py", line 122, in add_operation
test_1 |     self.blueprint.add_url_rule(flask_path, operation.endpoint_name, operation.function, methods=[method])
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/operation.py", line 234, in function
test_1 |     produces_decorator = self.__content_type_decorator
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/operation.py", line 271, in __content_type_decorator
test_1 |     mimetype = self.get_mimetype()
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/operation.py", line 165, in get_mimetype
test_1 |     if produces_json(self.produces):  # endpoint will return json
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/utils.py", line 121, in produces_json
test_1 |     return all(is_json_mimetype(mimetype) for mimetype in produces)
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/utils.py", line 121, in <genexpr>
test_1 |     return all(is_json_mimetype(mimetype) for mimetype in produces)
test_1 |   File "/usr/local/lib/python2.7/site-packages/connexion/utils.py", line 95, in is_json_mimetype
test_1 |     maintype, subtype = mimetype.split('/')  # type: str, str
test_1 | ValueError: need more than 1 value to unpack
```

What is the right way to return a flask.Response object using connexion?

**Comment by hjacobs** [comment]
1. returning flask.Response should work out of the box (I haven't tested "redirect"..), will check...
2. regarding the "produces" mimetype: The "produces" property needs to be a _list_ of mimetypes, see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields (obviously Connexion's error handling could be better..)

**Comment by jvgutierrez** [comment]
@hjacobs flask.Response is handled by Produces(BaseSerializer) class:
```python
class Produces(BaseSerializer):
    def __call__(self, function):
        """
        :type function: types.FunctionType
        :rtype: types.FunctionType
        """

        @functools.wraps(function)
        def wrapper(*args, **kwargs):
            url = flask.request.url
            data, status_code, headers = self.get_full_response(function(*args, **kwargs))
            logger.debug('Returning %s', url, extra={'url': url, 'mimetype': self.mimetype})
            if isinstance(data, flask.Response):  # if the function returns a Response object don't change it
                logger.debug('Endpoint returned a Flask Response', extra={'url': url, 'mimetype': data.mimetype})
                return data
```

BaseSerializer has associated the mimetype text/plain but I'm not able to set the endpoint output to text/plain, I tried with text/plain and text/plain; charset=utf-8 as is specified in the OpenAPI spec but I get the error that I pasted in the issue.

**Comment by jvgutierrez** [comment]
Ok.. the problem with the text/plain is solved. It was my fault:
```yaml
produces: text/plain
```
is not the the same than:
```yaml
produces:
  - text/plain
```

But it is still sending a 200 response with the text conversion of the flask.Response object:
```
curl http://192.168.99.101:8080/v1/dummy?test=1
<Response 209 bytes [302 FOUND]>
```
```
test_1 | 192.168.99.1 - - [03/Feb/2016:09:21:46 +0000] "GET /v1/dummy?test=1 HTTP/1.1" 200 32 "-" "curl/7.43.0"
```

**Comment by jvgutierrez** [comment]
Ok.. It's solved. The way to go is the following:
```python
def test_redirect_endpoint():
    headers = {'Location': 'http://www.google.com/'}
    return '', 302, headers
```
Instead of returning a real flask.Response object

**Comment by hjacobs** [comment]
hmm, IMHO real flask.Response should also work -- I will reopen the issue...

**Comment by jvgutierrez** [comment]
@hjacobs I can send you two tests showing the behaviour if it's helpful for you guys

**Comment by jvgutierrez** [comment]
Check https://github.com/jvgutierrez/connexion/commit/3697a5d72c40795fe5600491a609f8421d11322d
```
tests/test_app.py::test_redirect_endpoint PASSED
tests/test_app.py::test_redirect_response_endpoint FAILED
```
```
__________________________________________________________________________ test_redirect_response_endpoint __________________________________________________________________________

app = <connexion.app.App instance at 0x7f531002d4d0>

    def test_redirect_response_endpoint(app):
        app_client = app.app.test_client()
        resp = app_client.get('/v1.0/test-redirect-response-endpoint')
>       assert resp.status_code == 302
E       assert 500 == 302
E        +  where 500 = <Response streamed [500 INTERNAL SERVER ERROR]>.status_code
```
```
------------------------------------------------------------------------------- Captured stderr call --------------------------------------------------------------------------------
DEBUG:connexion.decorators.produces:Jsonifing http://localhost/v1.0/test-redirect-response-endpoint
DEBUG:connexion.decorators.parameter:Function Arguments: []
DEBUG:connexion.decorators.decorator:Getting data and status code
DEBUG:connexion.decorators.decorator:Got data and status code (200)
DEBUG:connexion.decorators.decorator:Getting data and status code
DEBUG:connexion.decorators.decorator:Got data and status code (200)
ERROR:test_app:Exception on /v1.0/test-redirect-response-endpoint [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/connexion/decorators/produces.py", line 126, in wrapper
    data = json.dumps(data, indent=2, cls=JSONEncoder)
  File "/usr/local/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/local/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/local/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/app/connexion/decorators/produces.py", line 43, in default
    return json.JSONEncoder.default(self, o)
  File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <Response 251 bytes [302 FOUND]> is not JSON serializable
```

**Comment by hjacobs** [comment]
@jvgutierrez :+1: thanks for reporting and the test (I was assuming it worked fine)

**Comment by rafaelcaricio** [comment]
@hjacobs I can take care of this issue.

**Comment by hjacobs** [comment]
fixed in https://github.com/zalando/connexion/releases/tag/1.0.52
