### ISSUE TITLE
Can't setup a custom response validator

### ISSUE THREAD

**Issue by adnaanbheda** [zalando/connexion#1342]
### Expected behaviour

Should be able to assign a custom response validator 

### Actual behaviour

```
class ResponseBodyValidator(decorators.validation.ResponseBodyValidator):
    def validate_schema(self, data, url):
        try:
            self.validator.validate(data)
        except Exception as exception:
            logger.error(
                "{url} validation error: {error}".format(url=url, error=exception),
                extra={"validator": "response"},
            )
            if MODE == "ON":
                raise exception
        return None
```

```
app.add_api(
    "openapi.yaml",
    resolver=RestyResolver(
        "api",
    ),
    strict_validation=(MODE != "OFF"),
    validate_responses=(MODE != "OFF"),
    validator_map={"response": ResponseBodyValidator},
)
```

Throws this error
```
Failed to add operation for GET /test/{query}
Traceback (most recent call last):
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/apis/abstract.py", line 209, in add_paths
    self.add_operation(path, method)
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/apis/abstract.py", line 175, in add_operation
    self._add_operation_internal(method, path, operation)
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/apis/flask_api.py", line 113, in _add_operation_internal
    function = operation.function
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/operations/abstract.py", line 353, in function
    response_decorator = self.__response_validation_decorator
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/operations/abstract.py", line 436, in __response_validation_decorator
    return ResponseValidator(self, self.get_mimetype())
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/decorators/validation.py", line 238, in __init__
    self.validator = ValidatorClass(schema, format_checker=draft4_format_checker)
TypeError: 'str' object is not callable
Failed to add operation for GET /test/1
Traceback (most recent call last):
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/apis/abstract.py", line 209, in add_paths
    self.add_operation(path, method)
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/apis/abstract.py", line 175, in add_operation
    self._add_operation_internal(method, path, operation)
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/apis/flask_api.py", line 113, in _add_operation_internal
    function = operation.function
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/operations/abstract.py", line 353, in function
    response_decorator = self.__response_validation_decorator
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/operations/abstract.py", line 436, in __response_validation_decorator
    return ResponseValidator(self, self.get_mimetype())
  File "/home/adnaan/.local/share/virtualenvs/test_connexion-Qe7M_k1Q/lib/python3.8/site-packages/connexion/decorators/validation.py", line 238, in __init__
    self.validator = ValidatorClass(schema, format_checker=draft4_format_checker)
TypeError: 'str' object is not callable

```
### Steps to reproduce

Try and create a custom response validator by assigning a custom validator class to the ```response``` key in ```validator_map```  in ```add_api```

### Additional info:

What I want to achieve here is a "mode" based validation on the responses and conditionally throw a validation error of the response.

So, let's say the value of MODE here is OFF, it shouldn't throw an error instead it should log the error and send back the original response.

For doing this, I tried to setup a response validator that catches the validation error and conditionally raises the exception.

This is only happening for a custom response validation, body/parameter custom validation work fine.

I'm open to alternative solutions to achieve this !

Output of the commands:

- `python --version`
Python 3.8.5
- `pip show connexion | grep "^Version\:"`
Version: 2.7.0

**Comment by RobbeSneyders** [comment]
Hi @adnaanbheda 

The custom response validator should subclass [`json_schema.Draft4ResponseValidator`](https://github.com/zalando/connexion/blob/df7ec12f4548438636ce5a5a6704fccce2dbc2dc/connexion/json_schema.py#L105) instead of `decorators.validation.ResponseBodyValidator`. The [docs](https://github.com/zalando/connexion/blob/main/docs/response.rst#custom-validator) are not very clear on this though, so we should update them to clarify.

**Comment by RobbeSneyders** [comment]
We should also clarify the [custom request & parameter validation](https://github.com/zalando/connexion/blob/main/docs/request.rst#custom-validators).

**Comment by RobbeSneyders** [comment]
Hi @adnaanbheda, removed my older comment as it was incorrect.

You should subclass `connexion.decorators.response.ResponseValidator` instead of `decorators.validation.ResponseBodyValidator`.
