### ISSUE TITLE
Import error for JSONschema

### ISSUE THREAD

**Issue by albertoZurini** [zalando/connexion#1349]
### Description

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/swagger_server/__main__.py", line 3, in <module>
    import connexion
  File "/usr/local/lib/python3.8/site-packages/connexion/__init__.py", line 3, in <module>
    from .apis import AbstractAPI  # NOQA
  File "/usr/local/lib/python3.8/site-packages/connexion/apis/__init__.py", line 1, in <module>
    from .abstract import AbstractAPI  # NOQA
  File "/usr/local/lib/python3.8/site-packages/connexion/apis/abstract.py", line 10, in <module>
    from ..operations import make_operation
  File "/usr/local/lib/python3.8/site-packages/connexion/operations/__init__.py", line 1, in <module>
    from .abstract import AbstractOperation  # noqa
  File "/usr/local/lib/python3.8/site-packages/connexion/operations/abstract.py", line 11, in <module>
    from ..decorators.response import ResponseValidator
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/response.py", line 12, in <module>
    from .validation import ResponseBodyValidator
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/validation.py", line 13, in <module>
    from ..json_schema import Draft4RequestValidator, Draft4ResponseValidator
  File "/usr/local/lib/python3.8/site-packages/connexion/json_schema.py", line 7, in <module>
    from openapi_spec_validator.handlers import UrlHandler
  File "/usr/local/lib/python3.8/site-packages/openapi_spec_validator/__init__.py", line 8, in <module>
    from openapi_spec_validator.validators import SpecValidator
  File "/usr/local/lib/python3.8/site-packages/openapi_spec_validator/validators.py", line 5, in <module>
    from openapi_schema_validator import OAS30Validator, oas30_format_checker
  File "/usr/local/lib/python3.8/site-packages/openapi_schema_validator/__init__.py", line 3, in <module>
    from openapi_schema_validator.shortcuts import validate
  File "/usr/local/lib/python3.8/site-packages/openapi_schema_validator/shortcuts.py", line 3, in <module>
    from openapi_schema_validator.validators import OAS30Validator
  File "/usr/local/lib/python3.8/site-packages/openapi_schema_validator/validators.py", line 1, in <module>
    from jsonschema import _legacy_validators, _utils, _validators
ImportError: cannot import name '_legacy_validators' from 'jsonschema' (/usr/local/lib/python3.8/site-packages/jsonschema/__init__.py)
```

### Expected behaviour

`import connexion` shouldn't throw

### Actual behaviour

`import connexion` throws the error

### Steps to reproduce

Swagger codegen
requirements.txt:
```
connexion == 2.6.0
python_dateutil == 2.6.0
setuptools >= 21.0.0
```

`python -m swagger_server`

### Additional info:

Output of the commands:

- `python --version` 3.8.8
- `pip show connexion | grep "^Version\:"` 2.2.0

**Comment by joe42** [comment]
connexion seems to be no longer supported. You probably get that error because connexion needs an old jsonschema version (I think `2.6.0`) and you have a newer version installed. If you are just starting I suggest looking for an alternative to connexion.

**Comment by albertoZurini** [comment]
I've found the problem: I am using Swagger Codegen with a script that merges the old code and the new code (when I edit the YAML); the problem is that the code was not updated correctly: I had to remove all the files and rebuild from zero the YAML and it did work... This is pretty strange given that I did not update the Codegen, so all the assets should have been compatible.
