### ISSUE TITLE
Airflow webserver starting issue 

### ISSUE THREAD

**Issue by IndrajeetTech2020** [zalando/connexion#1352]
### Description
```
 ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2021-04-19 13:26:53,316] {dagbag.py:448} INFO - Filling up the DagBag from /dev/null
[2021-04-19 13:26:55,622] {abstract.py:229} ERROR - Failed to add operation for GET /api/v1/connections
Traceback (most recent call last):
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/apis/abstract.py", line 209, in add_paths
    self.add_operation(path, method)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/apis/abstract.py", line 162, in add_operation
    operation = make_operation(
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/operations/__init__.py", line 8, in make_operation
    return spec.operation_cls.from_spec(spec, *args, **kwargs)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/operations/openapi.py", line 128, in from_spec
    return cls(
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/operations/openapi.py", line 75, in __init__
    super(OpenAPIOperation, self).__init__(
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/operations/abstract.py", line 96, in __init__
    self._resolution = resolver.resolve(self)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/resolver.py", line 40, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/resolver.py", line 66, in resolve_function_from_operation_id
    raise ResolverError(str(e), sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: columns>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 360, in webserver
    app = cached_app(None)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/airflow/www/app.py", line 135, in cached_app
    app = create_app(config=config, testing=testing)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/airflow/www/app.py", line 120, in create_app
    init_api_connexion(flask_app)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/airflow/www/extensions/init_views.py", line 171, in init_api_connexion
    api_bp = connexion_app.add_api(
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/apps/flask_app.py", line 57, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/apps/abstract.py", line 144, in add_api
    api = self.api_cls(specification,
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/apis/abstract.py", line 111, in __init__
    self.add_paths()
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/apis/abstract.py", line 216, in add_paths
    self._handle_add_operation_error(path, method, err.exc_info)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/apis/abstract.py", line 231, in _handle_add_operation_error
    raise value.with_traceback(traceback)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/resolver.py", line 61, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/connexion/utils.py", line 111, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/airflow/api_connexion/endpoints/connection_endpoint.py", line 26, in <module>
    from airflow.api_connexion.schemas.connection_schema import (
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/airflow/api_connexion/schemas/connection_schema.py", line 42, in <module>
    class ConnectionSchema(ConnectionCollectionItemSchema):  # pylint: disable=too-many-ancestors
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/marshmallow/schema.py", line 121, in __new__
    klass._declared_fields = mcs.get_declared_fields(
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/marshmallow_sqlalchemy/schema/sqlalchemy_schema.py", line 94, in get_declared_fields
    fields.update(mcs.get_auto_fields(fields, converter, opts, dict_cls))
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/marshmallow_sqlalchemy/schema/sqlalchemy_schema.py", line 104, in get_auto_fields
    {
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/marshmallow_sqlalchemy/schema/sqlalchemy_schema.py", line 105, in <dictcomp>
    field_name: field.create_field(
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/marshmallow_sqlalchemy/schema/sqlalchemy_schema.py", line 28, in create_field
    return converter.field_for(model, column_name, **self.field_kwargs)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/marshmallow_sqlalchemy/convert.py", line 171, in field_for
    return self.property2field(prop, **kwargs)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/marshmallow_sqlalchemy/convert.py", line 146, in property2field
    field_class = field_class or self._get_field_class_for_property(prop)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/marshmallow_sqlalchemy/convert.py", line 210, in _get_field_class_for_property
    column = prop.columns[0]
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1220, in __getattr__
    return self._fallback_getattr(key)
  File "/home/indrajeet/courses/mastering-apache-airflow/airflow-demand-planning/venv1/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 1194, in _fallback_getattr
    raise AttributeError(key)
AttributeError: columns
```

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by Ruwann** [comment]
Hi @IndrajeetTech2020 , it looks like this is caused by an error in `sqlalchemy` when connexion tries to resolve the operationId. Could you share a minimal reproducible example?
