### ISSUE TITLE
Issue with endpoints with body and path params

### ISSUE THREAD

**Issue by jvgutierrez** [zalando/connexion#141]
I'm having problems creating an endpoint like this one:
```yaml
  /test-mixed-params/{path_param}:
    post:
      summary: Test mixed params (path and body)
      operationId: fakeapi.hello.test_mixed_params
      parameters:
        - name: path_param
          type: string
          in: path
          required: true
        - name: body_param
          in: body
          required: true
```

When a request is sent to this endpoint the following error is generated:
```
TypeError: test_mixed_params() takes exactly 2 arguments (1 given)
```

I've committed a test case for this issue in https://github.com/jvgutierrez/connexion/commit/95fcdbeb18242832e3799e02e22ecc3c9698a5a7

Test case output:
```
DEBUG:connexion.decorators.validation:http://localhost/v1.0/test-mixed-params/1 validating parameters...
DEBUG:connexion.decorators.produces:Jsonifing http://localhost/v1.0/test-mixed-params/1
DEBUG:connexion.decorators.parameter:Function Arguments: ['path_param', 'body_param']
ERROR:test_app:Exception on /v1.0/test-mixed-params/1 [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/connexion/decorators/validation.py", line 192, in wrapper
    response = function(*args, **kwargs)
  File "/app/connexion/decorators/produces.py", line 117, in wrapper
    data, status_code, headers = self.get_full_response(function(*args, **kwargs))
  File "/app/connexion/decorators/response.py", line 70, in wrapper
    result = function(*args, **kwargs)
  File "/app/connexion/decorators/parameter.py", line 117, in wrapper
    return function(*args, **kwargs)
TypeError: test_mixed_params() takes exactly 2 arguments (1 given)
```

```
_________________________________________________________________________________ test_mixed_params _________________________________________________________________________________

app = <connexion.app.App instance at 0x7efe478df7a0>

    def test_mixed_params(app):
        app_client = app.app.test_client()
        resp = app_client.post('/v1.0/test-mixed-params/1', data=json.dumps('test'))
>       assert resp.status_code == 200
E       assert 500 == 200
E        +  where 500 = <Response streamed [500 INTERNAL SERVER ERROR]>.status_code

tests/test_app.py:731: AssertionError
```

**Comment by jvgutierrez** [comment]
Sorry guys... it was a problem on my side, I have to send Content-type header set to application/json.
BTW, according to flask API (http://flask.pocoo.org/docs/0.10/api/#flask.Request.json) in https://github.com/zalando/connexion/blob/master/connexion/decorators/parameter.py#L79 flask.request.get_json() should be used instead of flask.request.json
