### ISSUE TITLE
Using open api schema gives ValueError: Empty module name

### ISSUE THREAD

**Issue by MarcoRizk** [zalando/connexion#1432]
### Description
When loading an open api schema with the following code 
```
import connexion

app = connexion.App(__name__)
app.add_api('swagger.yaml')

application = app.app

if __name__ == '__main__':
    # run our standalone gevent server
    app.run(port=5000)
```
I get the following error stack.
```
Failed to add operation for GET /api/active-modules/
Traceback (most recent call last):
  File "venv/lib/python3.6/site-packages/connexion/apis/abstract.py", line 222, in add_paths
    self.add_operation(path, method)
  File "venv/lib/python3.6/site-packages/connexion/apis/abstract.py", line 186, in add_operation
    pass_context_arg_name=self.pass_context_arg_name
  File "venv/lib/python3.6/site-packages/connexion/operations/__init__.py", line 16, in make_operation
    return spec.operation_cls.from_spec(spec, *args, **kwargs)
  File "venv/lib/python3.6/site-packages/connexion/operations/swagger2.py", line 141, in from_spec
    **kwargs
  File "venv/lib/python3.6/site-packages/connexion/operations/swagger2.py", line 100, in __init__
    pass_context_arg_name=pass_context_arg_name
  File venv/lib/python3.6/site-packages/connexion/operations/abstract.py", line 101, in __init__
    self._resolution = resolver.resolve(self)
  File "venv/lib/python3.6/site-packages/connexion/resolver.py", line 44, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "venv/lib/python3.6/site-packages/connexion/resolver.py", line 70, in resolve_function_from_operation_id
    raise ResolverError(str(e), sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: Empty module name>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 5, in <module>
    app.add_api('swagger.yaml')
  File "venv/lib/python3.6/site-packages/connexion/apps/flask_app.py", line 65, in add_api
    api = super().add_api(specification, **kwargs)
  File "venv/lib/python3.6/site-packages/connexion/apps/abstract.py", line 161, in add_api
    options=api_options.as_dict())
  File "venv/lib/python3.6/site-packages/connexion/apis/abstract.py", line 119, in __init__
    self.add_paths()
  File "venv/lib/python3.6/site-packages/connexion/apis/abstract.py", line 229, in add_paths
    self._handle_add_operation_error(path, method, err.exc_info)
  File "venv/lib/python3.6/site-packages/connexion/apis/abstract.py", line 244, in _handle_add_operation_error
    raise value.with_traceback(traceback)
  File "venv/lib/python3.6/site-packages/connexion/resolver.py", line 65, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "venv/lib/python3.6/site-packages/connexion/utils.py", line 116, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 991, in _gcd_import
  File "<frozen importlib._bootstrap>", line 930, in _sanity_check
ValueError: Empty module name

Process finished with exit code 1

```

The only way I could get it to work is by changing the code to 
```import connexion
from connexion.mock import MockResolver

app = connexion.App(__name__)
app.add_api('swagger.yaml', resolver=MockResolver())

application = app.app

if __name__ == '__main__':
    # run our standalone gevent server
    app.run(port=5000)
```
can someone explain this behavior ? It doesn't mention having to use MockResolver any where in the docs

**Comment by RobbeSneyders** [comment]
Hi @MarcoRizk 
The stacktrace shows that cConnexion has problems resolving an operation id in your openapi spec. Please check our [documentation on routing](https://connexion.readthedocs.io/en/latest/routing.html) for more info on how to use the operation id. You should not use the MockResolver unless you want to run a mock server.

If you are still stuck, please provide a minimal reproducable example.

**Comment by MarcoRizk** [comment]
Thanks I want to run a mock server anyways so it works for me. I only wanted to understand why it was throwing that error.

> Hi @MarcoRizk The stacktrace shows that cConnexion has problems resolving an operation id in your openapi spec. Please check our [documentation on routing](https://connexion.readthedocs.io/en/latest/routing.html) for more info on how to use the operation id. You should not use the MockResolver unless you want to run a mock server.
> 
> If you are still stuck, please provide a minimal reproducable example.
