### ISSUE TITLE
ModuleNotFoundError: No module named 'people'

### ISSUE THREAD

**Issue by salvadorraymund** [zalando/connexion#1439]
### Description
Trying to run a Rest API using Flask and connexion[swagger-ui]

### Expected behaviour
Should work

### Actual behaviour
Throws Exception
```
Failed to add operation for GET /api/people
Usage: flask run [OPTIONS]

Error: While importing "server", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/apis/abstract.py", line 222, in add_paths
    self.add_operation(path, method)
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/apis/abstract.py", line 175, in add_operation
    operation = make_operation(
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/operations/__init__.py", line 16, in make_operation
    return spec.operation_cls.from_spec(spec, *args, **kwargs)
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/operations/swagger2.py", line 126, in from_spec
    return cls(
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/operations/swagger2.py", line 86, in __init__
    super().__init__(
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/operations/abstract.py", line 101, in __init__
    self._resolution = resolver.resolve(self)
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/resolver.py", line 44, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/resolver.py", line 68, in resolve_function_from_operation_id
    raise ResolverError(msg, sys.exc_info())
connexion.exceptions.ResolverError: <ResolverError: Cannot resolve operationId "people.read"! Import error was "No module named 'people'">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/server.py", line 11, in <module>
    app.add_api("swagger.yml")
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/apps/flask_app.py", line 65, in add_api
    api = super().add_api(specification, **kwargs)
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/apps/abstract.py", line 149, in add_api
    api = self.api_cls(specification,
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/apis/abstract.py", line 119, in __init__
    self.add_paths()
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/apis/abstract.py", line 229, in add_paths
    self._handle_add_operation_error(path, method, err.exc_info)
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/apis/abstract.py", line 244, in _handle_add_operation_error
    raise value.with_traceback(traceback)
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/resolver.py", line 65, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/Users/raysal/Documents/Python Projects/Rest APIs/Flask/People Rest API/.venv/lib/python3.9/site-packages/connexion/utils.py", line 116, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/opt/homebrew/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'people'
```

### Steps to reproduce
using Mac OS, Python 3.9.6

### Additional info:
using Mac OS, Python 3.9.6

Output of the commands:

- `python --version`
Python 3.9.6
- `pip show connexion | grep "^Version\:"`
Version 2.9.0

**Comment by Ruwann** [comment]
What does your folder structure look like?
Given operationId `people.read`, there should be a Python module `people` which contains the function `read`

**Comment by salvadorraymund** [comment]
Hello, Ruwan. Interestingly, my people.py folder resides in the same folder as my swagger.yml and server.py model.

**Comment by salvadorraymund** [comment]
I now have figured out the reason for this error.
1. I have edited my sys.path to include the location of the venv i created to store packages such as flask and connexion.
2. If i don't do this,  I won't be able to import those two packages.
3. That quickfix seems to have messed my sys.path. If I comment it out, I can use the people module.
How can I resolve this issue with paths? Thank you

**Comment by Ruwann** [comment]
You shouldn't need to mess around with your `sys.path`, I suspect by using `flask run` you are using another Flask installation that is different from the one in you virtualenv.

Can you create a new virtualenv, activate it and try again?

**Comment by salvadorraymund** [comment]
I was able to resolve by appending the location of the flask and connexion to sys.path in the server module. Thank you so much for the help!
