### ISSUE TITLE
File upload doesn't work

### ISSUE THREAD

**Issue by chriscoomber** [zalando/connexion#191]
I'm trying to upload a file with Swagger and Connexion, but the file part of the formData doesn't make it to my handler.

The relevant swagger.yaml is (the file is the 3rd parameter):
```
  /deployments/{deployment_id}/avatars/{avatar_filename}:
    put:
      tags:
      - "Avatars"
      summary: "Upload an avatar"
      operationId: "mypackage.controller.put_avatar"
      consumes:
      - "multipart/form-data"
      parameters:
      - $ref: "#/parameters/deployment_id"
      - $ref: "#/parameters/avatar_filename"
      - name: "avatar"
        in: "formData"
        description: "The avatar"
        required: true
        type: "file"
      responses:
        200:
          description: "Avatar updated"
        201:
          description: "Avatar uploaded"
```

My handler at `mypackage.controller.put_avatar` receives only the first two parameters, and was expecting: deployment_id, avatar_filename, avatar:
```
Traceback (most recent call last):
  File "/mysourcedir/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/mysourcedir/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mysourcedir/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mysourcedir/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mysourcedir/eggs/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mysourcedir/eggs/connexion-1.0.61-py2.7.egg/connexion/decorators/validation.py", line 192, in wrapper
    response = function(*args, **kwargs)
  File "/mysourcedir/eggs/connexion-1.0.61-py2.7.egg/connexion/decorators/produces.py", line 117, in wrapper
    data, status_code, headers = self.get_full_response(function(*args, **kwargs))
  File "/mysourcedir/eggs/connexion-1.0.61-py2.7.egg/connexion/decorators/response.py", line 70, in wrapper
    result = function(*args, **kwargs)
  File "/mysourcedir/eggs/connexion-1.0.61-py2.7.egg/connexion/decorators/parameter.py", line 125, in wrapper
    return function(*args, **kwargs)
TypeError: put_avatar() takes exactly 3 arguments (2 given)
```

I think this is an error in https://github.com/zalando/connexion/blob/master/connexion/decorators/parameter.py#L51.

In defining the wrapper, we take information from the flask request and provide it to the handler function. However, the `flask.request.files` are all missed.
`flask.request.form.items()` doesn't contain my file, because I think flask moves this to `flask.request.files`, which does contain my file.

I think this wrapper function should have an extra step:
- body parameters (json)
- query arguments
- form arguments
- **files**

**Comment by chriscoomber** [comment]
A similar problem in parameter.py is that the body is assumed to be JSON. My workaround for the above issue is to send a byte string in the body with content-type `application/octet-stream`, but naturally this isn't JSON.
