### ISSUE TITLE
Swagger 2.0 yaml and git head and pip install connextion fail

### ISSUE THREAD

**Issue by josephwinston** [zalando/connexion#220]
### Description
Loaded ```yaml``` into ```swaggerapi/swagger-editor```, Generate Server-> Python Flask, install connexion either from git (via ```python setup.py install```) or ```pip install connexion``` on both python 2 and python 3.  Running ```app.py``` gives the following traceback:

```
$ ~/anaconda/bin/python app.py 
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    app.add_api('swagger.yaml', arguments={'title': 'My App\n'})
  File "/home/jbw/anaconda/lib/python2.7/site-packages/connexion-2016.0.dev1-py2.7.egg/connexion/app.py", line 146, in add_api
    debug=self.debug)
  File "/home/jbw/anaconda/lib/python2.7/site-packages/connexion-2016.0.dev1-py2.7.egg/connexion/api.py", line 91, in __init__
    self.specification = compatibility_layer(self.specification)
  File "/home/jbw/anaconda/lib/python2.7/site-packages/connexion-2016.0.dev1-py2.7.egg/connexion/api.py", line 46, in compatibility_layer
    for response_code, response_def in method_def.get('responses', {}).items():
AttributeError: 'str' object has no attribute 'get'
$ ~/anaconda/bin/python app.py 
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    app.add_api('swagger.yaml', arguments={'title': 'My App\n'})
  File "/home/jbw/anaconda/lib/python2.7/site-packages/connexion-2016.0.dev1-py2.7.egg/connexion/app.py", line 146, in add_api
    debug=self.debug)
  File "/home/jbw/anaconda/lib/python2.7/site-packages/connexion-2016.0.dev1-py2.7.egg/connexion/api.py", line 91, in __init__
    self.specification = compatibility_layer(self.specification)
  File "/home/jbw/anaconda/lib/python2.7/site-packages/connexion-2016.0.dev1-py2.7.egg/connexion/api.py", line 46, in compatibility_layer
    for response_code, response_def in method_def.get('responses', {}).items():
AttributeError: 'str' object has no attribute 'get'

```

### Steps to reproduce
See about

### Additional info:

Output of the commands:

- `python --version`

```
Python 2.7.11 :: Anaconda 2.5.0 (64-bit)
```

- `pip show connexion | grep "^Version\:"`

```
Version: 2016.0.dev1
```

**Comment by hjacobs** [comment]
Could you paste your YAML snippet here? It looks like the structure is not what the code expects (string where a dict is expected).

**Comment by josephwinston** [comment]
The YAML works for other generated servers so I'm *assuming* that the code is valid.  Is there an easy way to have the parse tell me where the failure is in the YAML?

**Comment by rafaelcaricio** [comment]
@josephwinston Please update your Connexion version and try again. It should show a better error message this time.
