### ISSUE TITLE
Raise original exception while importing modules

### ISSUE THREAD

**Issue by tomas-fp** [zalando/connexion#250]
### Description

Currently, when importing Python modules dynamically while binding routes to Flask, if something is wrong with the loaded code there's only a generic `connexion` exception raised, so the original error is hidden and therefore there's not easy way to see what was the real error.

### Expected behaviour

Catch the original Python exception and raise it properly exposing it to higher layers instead of raising a generic error who tells you nothing.

### Actual behaviour

This is the error stack trace, which is not exposing the real problem:
```
ERROR:connexion.api:Failed to add operation for DELETE /api/reports/{report}
Traceback (most recent call last):
  File "/Users/taparicio/.pyenv/versions/3.5.1/lib/python3.5/site-packages/connexion/api.py", line 196, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/Users/taparicio/.pyenv/versions/3.5.1/lib/python3.5/site-packages/connexion/api.py", line 169, in add_operation
    resolver=self.resolver)
  File "/Users/taparicio/.pyenv/versions/3.5.1/lib/python3.5/site-packages/connexion/operation.py", line 172, in __init__
    resolution = resolver.resolve(self)
  File "/Users/taparicio/.pyenv/versions/3.5.1/lib/python3.5/site-packages/connexion/resolver.py", line 51, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/Users/taparicio/.pyenv/versions/3.5.1/lib/python3.5/site-packages/connexion/resolver.py", line 72, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/Users/taparicio/.pyenv/versions/3.5.1/lib/python3.5/site-packages/connexion/utils.py", line 109, in get_function_from_name
    function = deep_getattr(module, attr_path)
  File "/Users/taparicio/.pyenv/versions/3.5.1/lib/python3.5/site-packages/connexion/utils.py", line 91, in deep_getattr
    return functools.reduce(getattr, attr.split('.'), obj)
AttributeError: module 'api' has no attribute 'reports'
```

### Steps to reproduce

Just try breaking your dynamically loaded code.

### Additional info:

Output of the commands:

- Python `3.5.1`.
- Version: 1.0.98

**Comment by rafaelcaricio** [comment]
@tomas-fp could you please try the latest version of Connexion? Currently the latest is [`1.0.103`](https://github.com/zalando/connexion/releases/tag/1.0.103) and it actually changes the way we handle import errors.

**Comment by rafaelcaricio** [comment]
No feedback received. Closing issue for now. @tomas-fp feel free to open this issue again if the problem persists.
