### ISSUE TITLE
Crashes with `[Errno 32] Broken pipe` when changing angular.js $http requests

### ISSUE THREAD

**Issue by Shaun1** [zalando/connexion#258]
### Description
HTTP requests coming from an angular.js application cause connexion to crash because of a broken pipe.

### Expected behavior
`socket.error: [Errno 32] Broken pipe` should be handled by the connexion server & server should continue running.

### Actual behavior
Connexion crashes with the following:

```
Traceback (most recent call last):
  File "http_api.py", line 54, in <module>
    http_server.run(port=9000)
  File "/usr/local/lib/python2.7/dist-packages/connexion/app.py", line 254, in run
    self.app.run('0.0.0.0', port=self.port, debug=self.debug, **options)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 238, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 297, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 704, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe
```

### Steps to reproduce
- start connexion server
- load angular.js app that makes $http requests on an $interval
- change to another view that closes one request function on an $interval & starts another

### Additional info:

Output of the commands:

- `python --version`
    Python 2.7.3
- `pip show connexion | grep "^Version\:"`
    '1.0.109'

**Comment by Shaun1** [comment]
This may be a Flask problem

**Comment by Shaun1** [comment]
Here's how the connexion app was configured:
```
http_server = connexion.App(__name__, specification_dir='./swagger')
http_server.add_api('swagger.yaml')
# --- Uses flask_cors to allow cross-origin requests
CORS(http_server.app)
# --- A separate application running in another process
bus_interface.run()
http_server.run(port=9000)
```

**Comment by Shaun1** [comment]
changed to using tornado server & working fine - must be a flask issue.
