### ISSUE TITLE
python setup.py install fails with: ValueError: invalid literal for int() with base 10: '6rc1'

### ISSUE THREAD

**Issue by rjurney** [zalando/connexion#260]
### Description

pip install fails

### Expected bahaviour

Install complete

### Actual behaviour

Russells-MacBook-Pro-OLD-506:connexion-1.0.109 rjurney$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    py_major_version, py_minor_version, _ = (int(v.rstrip('+')) for v in platform.python_version_tuple())
  File "setup.py", line 23, in <genexpr>
    py_major_version, py_minor_version, _ = (int(v.rstrip('+')) for v in platform.python_version_tuple())
ValueError: invalid literal for int() with base 10: '6rc1'

### Steps to reproduce

pip install connexion

### Additional info:

Output of the commands:

- `python --version` Python 2.7.6rc1
- `pip show connexion | grep "^Version\:"` Nothing

**Comment by rafaelcaricio** [comment]
If you run `pip install connexion` it works fine:
```
(test-connexion-install) ➜  connexion git:(master) python --version
Python 3.6.0a3
(test-connexion-install) ➜  connexion git:(master) pip install connexion
Collecting connexion
  Using cached connexion-1.0.109-py3-none-any.whl
Collecting six>=1.7 (from connexion)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting flask>=0.10.1 (from connexion)
  Using cached Flask-0.11.1-py2.py3-none-any.whl
Collecting PyYAML>=3.11 (from connexion)
  Using cached PyYAML-3.11.zip
Collecting strict-rfc3339>=0.6 (from connexion)
  Using cached strict-rfc3339-0.7.tar.gz
Collecting requests>=2.9.1 (from connexion)
  Using cached requests-2.11.0-py2.py3-none-any.whl
Collecting jsonschema>=2.5.1 (from connexion)
  Using cached jsonschema-2.5.1-py2.py3-none-any.whl
Collecting swagger-spec-validator>=2.0.2 (from connexion)
  Using cached swagger_spec_validator-2.0.2.tar.gz
Collecting Werkzeug>=0.7 (from flask>=0.10.1->connexion)
  Using cached Werkzeug-0.11.10-py2.py3-none-any.whl
Collecting Jinja2>=2.4 (from flask>=0.10.1->connexion)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting itsdangerous>=0.21 (from flask>=0.10.1->connexion)
  Using cached itsdangerous-0.24.tar.gz
Collecting click>=2.0 (from flask>=0.10.1->connexion)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /Users/rcaricio/.virtualenvs/test-connexion-install/lib/python3.6/site-packages (from swagger-spec-validator>=2.0.2->connexion)
Collecting MarkupSafe (from Jinja2>=2.4->flask>=0.10.1->connexion)
  Using cached MarkupSafe-0.23.tar.gz
Building wheels for collected packages: PyYAML, strict-rfc3339, swagger-spec-validator, itsdangerous, MarkupSafe
  Running setup.py bdist_wheel for PyYAML ... done
  Stored in directory: /Users/rcaricio/Library/Caches/pip/wheels/4a/bf/14/d79994d19a59d4f73efdafb8682961f582d45ed6b459420346
  Running setup.py bdist_wheel for strict-rfc3339 ... done
  Stored in directory: /Users/rcaricio/Library/Caches/pip/wheels/29/08/b5/937d8759c71b4517c22b145d32a71cdbb4f2caa950de4d8a11
  Running setup.py bdist_wheel for swagger-spec-validator ... done
  Stored in directory: /Users/rcaricio/Library/Caches/pip/wheels/cd/4e/f7/72383ffb703ce95cfef02c98b441c1c4d764595a314f061b1b
  Running setup.py bdist_wheel for itsdangerous ... done
  Stored in directory: /Users/rcaricio/Library/Caches/pip/wheels/fc/a8/66/24d655233c757e178d45dea2de22a04c6d92766abfb741129a
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /Users/rcaricio/Library/Caches/pip/wheels/a3/fa/dc/0198eed9ad95489b8a4f45d14dd5d2aee3f8984e46862c5748
Successfully built PyYAML strict-rfc3339 swagger-spec-validator itsdangerous MarkupSafe
Installing collected packages: six, Werkzeug, MarkupSafe, Jinja2, itsdangerous, click, flask, PyYAML, strict-rfc3339, requests, jsonschema, swagger-spec-validator, connexion
Successfully installed Jinja2-2.8 MarkupSafe-0.23 PyYAML-3.11 Werkzeug-0.11.10 click-6.6 connexion-1.0.109 flask-0.11.1 itsdangerous-0.24 jsonschema-2.5.1 requests-2.11.0 six-1.10.0 strict-rfc3339-0.7 swagger-spec-validator-2.0.2

```

You reported that you expect the `pip install connexion` to work, **it works**. Please notice that `python setup.py install` is **a different command**. Indeed the error occurs when trying to run it.

```
(test-connexion-install) ➜  connexion git:(master) python setup.py install
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    py_major_version, py_minor_version, _ = (int(v.rstrip('+')) for v in platform.python_version_tuple())
  File "setup.py", line 23, in <genexpr>
    py_major_version, py_minor_version, _ = (int(v.rstrip('+')) for v in platform.python_version_tuple())
ValueError: invalid literal for int() with base 10: '0a3'
```

Just to make this issue clear.

**Comment by hjacobs** [comment]
Released in https://github.com/zalando/connexion/releases/tag/1.0.112
