### ISSUE TITLE
Javascript Regex Literal Pattern Format Support (Perl Format)

### ISSUE THREAD

**Issue by ja-b** [zalando/connexion#269]
### Description
For the pattern field on parameters, the validation performed seems to be expecting a string format of a regular expression (surrounded by quotes) instead of the format of a Javascript Regex Literal (surrounded by forward slashes).

### Expected bahaviour
I'm expecting connexion to evaluate a regex in the form of `/[a-zA-Z0-9]+/` ,the format of a Javascript Regex Literal in the [Json Schema Standard](http://json-schema.org/latest/json-schema-validation.html#anchor33)

### Actual behaviour
If I give the regex in a string form, `"[a-zA-Z0-9]+"`, everything behaves as normal. However, if I give the regex in the literal form `/[a-zA-Z0-9]+/`, then I receive a 400 with the following response.

```
{
  "status": 400,
  "type": "about:blank",
  "detail": "u'UBU6' does not match '/[a-zA-Z0-9]+/'\n\nFailed validating 'pattern' in schema:\n    {'description': 'Filter by instrument symbology. Full instrument symbology needs to be provided.',\n     'in': 'query',\n     'name': 'symbol',\n     'pattern': '/[a-zA-Z0-9]+/',\n     'type': 'string'}\n\nOn instance:\n    u'UBU6'",
  "title": "Bad Request"
}

```

### Steps to reproduce
Simply create a spec using the literal format of a pattern field.

### Additional info:

Output of the commands:

- `python --version` => Python 2.7.6
- `pip show connexion | grep "^Version\:"` => Version: 1.0.103

**Comment by hjacobs** [comment]
Sorry, but the `pattern` property MUST be a string as defined here (you linked it yourself): http://json-schema.org/latest/json-schema-validation.html#anchor33

You can also find an example here: http://json-schema.org/example2.html

So I don't see any issue with Connexion here, it behaves according to the OpenAPI specification.

**Comment by ja-b** [comment]
I completely misinterpreted that line, sorry about that.  In that case, everything works perfectly. I'll close this issue.

Just for some context here, this whole thing kinda stems from the python client generator on swagger codegen, which has recently required that I put my regexes in the perl format, as dictated by this error.

```
Exception in thread "main" java.lang.RuntimeException: Could not process operation:
  Tag: Settlements
  Operation: app.get_sets
  Resource: get /sets
  Definitions: {settlement=io.swagger.models.ModelImpl@27ea7e11, errorModel=io.swagger.models.ModelImpl@eb8f307b}
  Exception: Pattern must follow the Perl /pattern/modifiers convention. ^[a-zA-Z0-9]+:[a-zA-Z0-9]+$ is not valid.
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:796)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:688)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:376)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:223)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:36)
Caused by: java.lang.IllegalArgumentException: Pattern must follow the Perl /pattern/modifiers convention. ^[a-zA-Z0-9]+:[a-zA-Z0-9]+$ is not valid.
	at io.swagger.codegen.languages.PythonClientCodegen.postProcessPattern(PythonClientCodegen.java:202)
	at io.swagger.codegen.languages.PythonClientCodegen.postProcessParameter(PythonClientCodegen.java:183)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:2380)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1961)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:744)
```

So I figured there must have been a change to the specification.
