### ISSUE TITLE
return a file as response

### ISSUE THREAD

**Issue by gustavo-freitas-movile** [zalando/connexion#324]
### Description

When i code my swagger on editor.swagger.io , its work properly. however when i try to run connexion, i got the following execution error:

```
swagger_spec_validator.common.SwaggerValidationError: {'description': 'Download static files', 'schema': {'description': 'binary file', 'type': 'file'}} is not valid under any of the given schemas
```

I can not found a good example how to return a file as response. Someone can help me?
### Expected bahaviour

```
paths:
  /download/{filename}:
    get:
      tags:
      - "files"
      description: |
        Download static files
      operationId: "controllers.static_controller.download_get"
      parameters:
      - name: "filename"
        in: "path"
        description: "Issue number"
        required: true
        type: "string"
      responses:
        200:
          description: "Download static files"
          schema:
            description: "binary file"
            type: "file"
            #$ref: "#/definitions/Issue"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      security:
      - UserSecurity: []
```
### Actual behaviour

```
ile "/usr/local/lib/python3.5/dist-packages/connexion/app.py", line 149, in add_api
    debug=self.debug)
  File "/usr/local/lib/python3.5/dist-packages/connexion/api.py", line 109, in __init__
    validate_spec(spec)
  File "/usr/local/lib/python3.5/dist-packages/swagger_spec_validator/validator20.py", line 82, in validate_spec
    http_handlers=http_handlers)
  File "/usr/local/lib/python3.5/dist-packages/swagger_spec_validator/common.py", line 22, in wrapper
    sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/swagger_spec_validator/common.py", line 17, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/swagger_spec_validator/validator20.py", line 125, in validate_json
    cls=Draft4Validator)
  File "/usr/local/lib/python3.5/dist-packages/swagger_spec_validator/ref_validators.py", line 34, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/usr/local/lib/python3.5/dist-packages/jsonschema/validators.py", line 123, in validate
    raise error
swagger_spec_validator.common.SwaggerValidationError: {'description': 'Download static files', 'schema': {'description': 'binary file', 'type': 'file'}} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['get']['properties']['responses']['patternProperties']['^([0-9]{3})$|^(default)$']:
    {'oneOf': [{'$ref': '#/definitions/response'},
               {'$ref': '#/definitions/jsonReference'}]}

On instance['paths']['/download/{filename}']['get']['responses']['200']:
    {'description': 'Download static files',
     'schema': {'description': 'binary file', 'type': 'file'}}

```
### Steps to reproduce

```
./run.sh 
[2016-10-24 12:40:46 -0200] [8834] [INFO] Starting gunicorn 19.6.0
[2016-10-24 12:40:46 -0200] [8834] [INFO] Listening at: http://0.0.0.0:8080 (8834)
[2016-10-24 12:40:46 -0200] [8834] [INFO] Using worker: gevent
[2016-10-24 12:40:46 -0200] [8837] [INFO] Booting worker with pid: 8837
[2016-10-24 12:40:46 -0200] [8838] [INFO] Booting worker with pid: 8838
[2016-10-24 12:40:46 -0200] [8837] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/swagger_spec_validator/common.py", line 17, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/swagger_spec_validator/validator20.py", line 125, in validate_json
    cls=Draft4Validator)
  File "/usr/local/lib/python3.5/dist-packages/swagger_spec_validator/ref_validators.py", line 34, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/usr/local/lib/python3.5/dist-packages/jsonschema/validators.py", line 123, in validate
    raise error
jsonschema.exceptions.ValidationError: {'description': 'Download static files', 'schema': {'description': 'binary file', 'type': 'file'}} is not valid under any of the given schemas

Failed validating 'oneOf' in schema['properties']['paths']['patternProperties']['^/']['properties']['get']['properties']['responses']['patternProperties']['^([0-9]{3})$|^(default)$']:
    {'oneOf': [{'$ref': '#/definitions/response'},
               {'$ref': '#/definitions/jsonReference'}]}

On instance['paths']['/download/{filename}']['get']['responses']['200']:
    {'description': 'Download static files',
     'schema': {'description': 'binary file', 'type': 'file'}}

During handling of the above exception, another exception occurred:

cat run.sh 
#gunicorn -w 9 -b 0.0.0.0:8080 wsgi -t 3600 -k gevent
gunicorn -w 2 -b 0.0.0.0:8080 wsgi -t 3600 -k gevent
#gunicorn -w 2 -b 0.0.0.0:8080 wsgi -t 3600 -k gevent

#celery -A wsgi worker --loglevel=info


my wsgi.py

if __name__ == "__main__":
    #app_run()
    application.run() #(threaded=True)
    #application.run(host='0.0.0.0',port=8080)


```
### Additional info:

pip3 show connexion | grep "^Version:"
Version: 1.0.129
python3 --version
Python 3.5.2

Output of the commands:
- `python --version`
- `pip show connexion | grep "^Version\:"`

**Comment by cloojure** [comment]
Any movement on this issue?

**Comment by rafaelcaricio** [comment]
@cloojure From what I can see in the history of this issue--I think the problem is in the swagger_spec lib.

**Comment by dimbleby** [comment]
I believe that the release of swagger-spec-validator 2.0.4 fixes this.

**Comment by hjacobs** [comment]
@gustavo-freitas-movile can you check whether the new `swagger-spec-validator` fixes the issue for you as mentioned by @dimbleby ?

**Comment by gustavo-freitas-movile** [comment]
yes, it have been fixed.

Thanks
