### ISSUE TITLE
Unicode Strings in Response body

### ISSUE THREAD

**Issue by LeenaBhegade** [zalando/connexion#395]
### Description
I am using Python 2.7 , connexion == 1.0.129

I am using connexion for writing my api endpoints. In the code I retrieve unicode strings ( for example: £ ) from database, create a dictionary and return it to client. Initially I assumed connexion will support utf-8 encoding and I don't have to make any additional changes to the configuration. 
When I did a  GET/ request  to my endpoint (which is further retrieving data from database and sending back response) , below is what I get on client (browser ) side

 {
        "user": 123, 
        "format": "\u00a3", 
        "id": 10, 
  }

The unicode strings are escaped and £ is not getting printed as expected. 

After reading more about encoding I came through Flask configuration variable JSON_AS_ASCII  to not encode strings to ASCII and output strings as-is and return unicode strings.
 I set the JSON_AS_ASCII in the app.app.config['JSON_AS_ASCII']=False.After running the code again I triggered a get request and got another

UnicodeEncodeError: 'ascii' codec can't encode character u'\xa3' in position 991: ordinal not in range(128)

After looking at code I noticed that the failure is caused during serialisation of the json response in decorators.produces class. 
The method Jsonifier.dumps() in produces class fails while returning the json response ---->
 "return {}\n".format(json.dumps(data, indent=2))

I checked the implementation on json.dumps in  flask.json.dumps() and noticed that the json message is not encoded before returning. the method is using keyword argument "encoding" for encoding the json message and currently it is "none" instead of "utf-8" ( No keyword argument is passed to Flask.json.dumps() from connexion currently )

 
### Expected behaviour
 Response on browser
 {
        "user": 123, 
        "format": "£", 
        "id": 10, 
  }

### Actual behaviour
Response on browser
{
        "user": 123, 
        "format": "\u00a3", 
        "id": 10, 
  }

### Additional info:
The connexion project was created from swagger.io

### Questions 
Is there any way to set a set the keyword argument "encoding:utf-8"  to flask.json.dumps() in  connexion or do I need to use python 3  ?

Is there a configuration parameter in connexion which  sets the  keyword argument encoding = "utf-8"  ?

I am very new to this framework so please correct me if I have missed important information while implementation.

**Comment by rafaelcaricio** [comment]
@LeenaBhegade Thank you for reporting this issue. There is no code in Connexion, that I am aware of, which deals with encoding in the response. So there is no Connexion options for that. Maybe you could send a Pull Request fixing this. Seems like you already found out that we are missing to pass the correct encoding. Does it fixed the issue for you?

**Comment by LeenaBhegade** [comment]
Hi @rafaelcaricio 

Thank you for your response
I think adding the parameter "unicode=utf-8" will fix the issue. 
I am happy to send a pull request for this fix.

Thanks

**Comment by LeenaBhegade** [comment]
Hi @rafaelcaricio,

I have created a pull request for the issue discussed above. Please review and confirm if it can be merged. 
https://github.com/zalando/connexion/pull/397
I have tested the changes at my side and responses are  encoded and printed as expected.
Thanks,
Leena

**Comment by rafaelcaricio** [comment]
Fixed by #397

**Comment by wicope** [comment]
Hi, i use for python 3.4:
```
        if six.PY2:
            json_content = json.dumps(data, indent=2, encoding="utf-8")
        else:
            json_content = json.dumps(data, indent=2, ensure_ascii=False)
```

**Comment by rafaelcaricio** [comment]
@wicope Is the latest version resulting in problems with your environment using Python 3.4 ?

**Comment by wicope** [comment]
```
# pip3 list
connexion (1.1.5)

# python -V
Python 2.7.6
# python3 -V
Python 3.4.3
```

i use: python3 app.py

**Comment by rafaelcaricio** [comment]
@wicope Have you defined the `operationId` attribute in all your endpoints in your Swagger definition?

**Comment by wicope** [comment]
@rafaelcaricio 

I understand the route to the method:
```
# ls
enforcedefaults-api.yaml
enforcedefaults.py
```
[enforcedefaults-api.yaml](https://github.com/zalando/connexion/blob/master/examples/enforcedefaults/enforcedefaults-api.yaml)
```
paths:
  /echo:
    post:
      description: Echo passed data
      operationId: enforcedefaults.echo
```
[enforcedefaults.py](https://github.com/zalando/connexion/blob/master/examples/enforcedefaults/enforcedefaults.py)
```
def echo(data):
      return data
```

---------
My case is a bit different on the route:
```
$ tree
├── python-flask-server
│   ├── app.py
│   ├── controllers
│   │   ├── default_controller.py   <---- here method: preocr_post
│   └── swagger
│       └── swagger.yaml
├── swagger.yaml
```

├── swagger.yaml
```
paths:
  /preocr:
    operationId: "controllers.default_controller.preocr_post"
```

├── python-flask-server
│   ├── controllers
│   │   ├── default_controller.py
```
def preocr_post(file):
    ...
    return json.loads(stdoutdata)
```

The error is:
```
root@53cf82918e9d:~/app# connexion run swagger.yaml -v
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/swagger_spec_validator/common.py", line 17, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/swagger_spec_validator/validator20.py", line 125, in validate_json
    cls=Draft4Validator)
  File "/usr/local/lib/python3.4/dist-packages/swagger_spec_validator/ref_validators.py", line 34, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/usr/local/lib/python3.4/dist-packages/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 'operationId' does not match any of the regexes: '^x-'

Failed validating 'additionalProperties' in schema['properties']['paths']['patternProperties']['^/']:
    {'additionalProperties': False,
     'patternProperties': {'^x-': {'$ref': '#/definitions/vendorExtension'}},
     'properties': {'$ref': {'type': 'string'},
                    'delete': {'$ref': '#/definitions/operation'},
                    'get': {'$ref': '#/definitions/operation'},
                    'head': {'$ref': '#/definitions/operation'},
                    'options': {'$ref': '#/definitions/operation'},
                    'parameters': {'$ref': '#/definitions/parametersList'},
                    'patch': {'$ref': '#/definitions/operation'},
                    'post': {'$ref': '#/definitions/operation'},
                    'put': {'$ref': '#/definitions/operation'}},
     'type': 'object'}

On instance['paths']['/preocr']:
    {'operationId': 'controllers.default_controller.preocr_post',
     'post': {'consumes': ['multipart/form-data'],
              'parameters': [{'description': 'The uploaded file data',
                              'in': 'formData',
                              'name': 'file',
                              'required': True,
                              'type': 'file'}],
              'produces': ['application/json'],
              'responses': {'200': {'description': 'OK',
                                    'schema': {'$ref': '#/definitions/Mercadona'}},
                            'default': {'description': 'unexpected '
                                                       'error',
                                        'schema': {'$ref': '#/definitions/Error'}}}}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/connexion", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/connexion/cli.py", line 144, in run
    **api_extra_args)
  File "/usr/local/lib/python3.4/dist-packages/connexion/app.py", line 168, in add_api
    validator_map=self.validator_map)
  File "/usr/local/lib/python3.4/dist-packages/connexion/api.py", line 108, in __init__
    validate_spec(spec)
  File "/usr/local/lib/python3.4/dist-packages/swagger_spec_validator/validator20.py", line 82, in validate_spec
    http_handlers=http_handlers)
  File "/usr/local/lib/python3.4/dist-packages/swagger_spec_validator/common.py", line 22, in wrapper
    sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.4/dist-packages/swagger_spec_validator/common.py", line 17, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/swagger_spec_validator/validator20.py", line 125, in validate_json
    cls=Draft4Validator)
  File "/usr/local/lib/python3.4/dist-packages/swagger_spec_validator/ref_validators.py", line 34, in validate
    instance_cls(schema, *args, **kwargs).validate(instance)
  File "/usr/local/lib/python3.4/dist-packages/jsonschema/validators.py", line 130, in validate
    raise error
swagger_spec_validator.common.SwaggerValidationError: 'operationId' does not match any of the regexes: '^x-'

Failed validating 'additionalProperties' in schema['properties']['paths']['patternProperties']['^/']:
    {'additionalProperties': False,
     'patternProperties': {'^x-': {'$ref': '#/definitions/vendorExtension'}},
     'properties': {'$ref': {'type': 'string'},
                    'delete': {'$ref': '#/definitions/operation'},
                    'get': {'$ref': '#/definitions/operation'},
                    'head': {'$ref': '#/definitions/operation'},
                    'options': {'$ref': '#/definitions/operation'},
                    'parameters': {'$ref': '#/definitions/parametersList'},
                    'patch': {'$ref': '#/definitions/operation'},
                    'post': {'$ref': '#/definitions/operation'},
                    'put': {'$ref': '#/definitions/operation'}},
     'type': 'object'}

On instance['paths']['/preocr']:
    {'operationId': 'controllers.default_controller.preocr_post',
     'post': {'consumes': ['multipart/form-data'],
              'parameters': [{'description': 'The uploaded file data',
                              'in': 'formData',
                              'name': 'file',
                              'required': True,
                              'type': 'file'}],
              'produces': ['application/json'],
              'responses': {'200': {'description': 'OK',
                                    'schema': {'$ref': '#/definitions/Mercadona'}},
                            'default': {'description': 'unexpected '
                                                       'error',
                                        'schema': {'$ref': '#/definitions/Error'}}}}}
```

What i can do? What do you think? Thank you very much.

**Comment by rafaelcaricio** [comment]
From your stacktrace:
```
    {'operationId': 'controllers.default_controller.preocr_post',
     'post': {'consumes': ['multipart/form-data'],
              'parameters': [{'description': 'The uploaded file data',
                              'in': 'formData',
                              'name': 'file',
                              'required': True,
                              'type': 'file'}],
              'produces': ['application/json'],
              'responses': {'200': {'description': 'OK',
                                    'schema': {'$ref': '#/definitions/Mercadona'}},
                            'default': {'description': 'unexpected '
                                                       'error',
                                        'schema': {'$ref': '#/definitions/Error'}}}}}
```

You are adding the `operationId` attribute in the wrong place. The `operationId` attribute should be inside the method object of the path definition:

```
    {
     'post': {'consumes': ['multipart/form-data'],
'operationId': 'controllers.default_controller.preocr_post',
              'parameters': [{'description': 'The uploaded file data',
                              'in': 'formData',
                              'name': 'file',
                              'required': True,
                              'type': 'file'}],
              'produces': ['application/json'],
              'responses': {'200': {'description': 'OK',
                                    'schema': {'$ref': '#/definitions/Mercadona'}},
                            'default': {'description': 'unexpected '
                                                       'error',
                                        'schema': {'$ref': '#/definitions/Error'}}}}}
```

**Comment by rafaelcaricio** [comment]
@wicope pls see the comment above. Also please open a new issue. This is completely not related to the issue we are commenting on.
