### ISSUE TITLE
Regression: module 'connexion.request' has no attribute 'user'

### ISSUE THREAD

**Issue by hjacobs** [zalando/connexion#433]
Another regression bug. #432 added support for `flask.request.user`, but we actually "promoted" `connexion.request` at some point (also mentioned in the docs). `connexion.request.user` no longer works:

```
[2017-04-05 17:27:53,592] ERROR in app: Exception on /aws-accounts/123456789012/roles/hjacobs/credentials [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/decorator.py", line 66, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/security.py", line 90, in wrapper
    return function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/validation.py", line 299, in wrapper
    return function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/decorator.py", line 42, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/parameter.py", line 195, in wrapper
    return function(**kwargs)
  File "/app.py", line 49, in get_credentials
    uid = connexion.request.user
AttributeError: module 'connexion.request' has no attribute 'user'
```

**Comment by rafaelcaricio** [comment]
This is ok to add back. But it will be available only for the Flask backend.

**Comment by hjacobs** [comment]
@rafaelcaricio how would you add it? `connexion.request` is now a module...

**Comment by rafaelcaricio** [comment]
I think we need to re-organize the current codebase to not break existing applications using Connexion's 1.x series.

Do you think we should not add this back?

**Comment by hjacobs** [comment]
@rafaelcaricio I think we should add it back! :smile:
