### ISSUE TITLE
JSON References for Parameters Not Supported

### ISSUE THREAD

**Issue by iwsmith** [zalando/connexion#46]
Hello all,

If you are using references in a parameter list an error is thrown: ``body_parameters = [parameter for parameter in self.parameters if parameter['in'] == 'body']``

An example of using a reference is included in the first definition of my swagger file:

Full Swagger def:
```
# Example YAML to get you started quickly.
# Be aware that YAML has indentation based scoping.
# Code completion support is available so start typing for available options.
swagger: '2.0'

# This is your document metadata
info:
  version: "0.0.1"
  title: Babel 

parameters:
  paper_id:
    name: paper_id
    description: Publisher assigned identifier of a paper
    type: string
    in: path
    required: true
  publisher:
    in: path
    name: publisher
    description: Publisher to perform this operation on
    type: string
    required: true
    enum:
    - aminer
    - arxiv
    - dblp 
    - jstor
    - mas
    - plos
    - pubmed

    
# Describe your paths here
paths:
  /recommendation/{publisher}/{paper_id}:
    get:
      description: Generates recommendations for `paper_id`
      operationId: app.echo
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/paper_id'
        - $ref: '#/parameters/publisher'
        - in: query
          name: limit
          default: 5
          maximum: 10
          minimum: 1
          required: false
          type: integer
          description: Maximum number of recommendations to return
        - in: query
          name: algorithm
          required: false
          type: string
          description: Algorithm to generate recommendations with. If not provided a random algorithm will be used.
          enum:
          - ef_expert
          - ef_classic
        - in: query
          name: client_id
          required: false
          type: string
          description: Identifier provided by the platform to clients to track client usage. If you have one please use it.
      # Expected responses for this operation:
      responses:
        # Response code
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Recommendations"
            
  /search:
    get:
      description: Searches metadata for known papers
      produces:
        - application/json
      parameters:
        - in: query
          name: query
          description: Query text
          required: true
          type: string
        - in: query
          name: publishers
          description: Publishers to restrict search to.
          type: array
          items:
            type: string
          collectionFormat: multi
        - in: query
          name: start
          description: For pagination. Use ``next`` value from a previous call.
          type: integer
      responses:
        "200":
          description: Search results
          schema: 
            $ref: "#/definitions/SearchResults"
            
  /metadata/{publisher}/{paper_id}:
    get:
      description: Returns metadata for a specific paper
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/paper_id'
        - $ref: '#/parameters/publisher'
      responses:
        "200":
          description: Metadata
        "400":
          description: No metadata found 
            
definitions:
  Recommendation:
    properties:
      paper_id:
        type: string
      publisher:
        type: string
  Recommendations:
    properties:
      transaction_id:
        type: string
        description: An identifier for this transaction. Use this when calling /feedback
      results:
        type: array
        items:
          $ref: '#/definitions/Recommendation'
  SearchResult:
    properties:
      paper_id:
        type: string
        description: ID of paper
      publisher:
        type: string
        description: Publisher name
      score:
        type: number
        description: Relevancy score. Higher is better.
  SearchResults:
    properties:
      count:
        type: integer
        description: Number of search results
      next:
        type: integer
        description: Value to provide for pagination
      start:
        type: integer
        description: Start value for this result.
      results:
        type: array
        items:
          $ref: '#/definitions/SearchResult'
```

Full Error
```
ERROR:connexion.api:Failed to add operation for GET /recommendation/<publisher>/<paper_id>
Traceback (most recent call last):
  File "/Users/iwsmith/bin/loopy/lib/python2.7/site-packages/connexion/api.py", line 120, in add_paths
    self.add_operation(method, path, endpoint)
  File "/Users/iwsmith/bin/loopy/lib/python2.7/site-packages/connexion/api.py", line 105, in add_operation
    self.blueprint.add_url_rule(path, operation.endpoint_name, operation.function, methods=[method])
  File "/Users/iwsmith/bin/loopy/lib/python2.7/site-packages/connexion/operation.py", line 128, in function
    validation_decorator = self.__validation_decorator
  File "/Users/iwsmith/bin/loopy/lib/python2.7/site-packages/connexion/operation.py", line 223, in __validation_decorator
    if self.body_schema:
  File "/Users/iwsmith/bin/loopy/lib/python2.7/site-packages/connexion/operation.py", line 89, in body_schema
    body_parameters = [parameter for parameter in self.parameters if parameter['in'] == 'body']
```

Please let me know if there is anything else I can do to help with this issue.

Thanks!

**Comment by hjacobs** [comment]
Thanks for reporting this issue, we will look into it --- obviously Connexion should eventually work out of the box with any Swagger file, but we are not there yet.

**Comment by hjacobs** [comment]
Fixed in 0.8.5: https://github.com/zalando/connexion/releases/tag/0.8.5

**Comment by hjacobs** [comment]
Please note that parameter validation is not supported yet (only body schema).

**Comment by hjacobs** [comment]
@iwsmith I also updated my Connexion example to use parameter references: https://github.com/hjacobs/connexion-example

**Comment by iwsmith** [comment]
Awesome! Just tried it out and it works, thanks!
