### ISSUE TITLE
Using unicode instead of str?

### ISSUE THREAD

**Issue by turdusmerula** [zalando/connexion#485]
### Description
In `connexion/decorators/parameter.py` having `string` mapped to `str` prevents to pass any non ASCII data inside requests parameters even when properly translated inside URL.

Example: I need to filter inside a REST request by some symbol prefix and one of them is 'µ' which is translated in URL to `%C2%B5`:
`curl -X GET --header 'Accept: application/json' 'http://localhost:8200/api/unitprefixes?symbol=%C2%B5'`
This leads to this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/validation.py", line 290, in wrapper
    response = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/produces.py", line 118, in wrapper
    data, status_code, headers = self.get_full_response(function(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/parameter.py", line 134, in wrapper
    kwargs[key] = get_val_from_param(value, query_param)
  File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/parameter.py", line 62, in get_val_from_param
    return make_type(value, query_param["type"])
  File "/usr/local/lib/python2.7/dist-packages/connexion/decorators/parameter.py", line 48, in make_type
    return type_func(value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb5' in position 0: ordinal not in range(128)
```

`str` seems way too much restrictive as it prevents to pass any valid but non ASCII character inside a request.

I modified the mapping to have my requests working well:
```
TYPE_MAP = {'integer': int,
            'number': float,
            'string': unicode,
            'boolean': boolean,
            'array': list,
            'object': dict}  # map of swagger types to python types

```
Am I wrong somewhere or is this limitation perfectly legitimate due to some standard?

### Additional info:

Output of the commands:

- `python --version`: Python 2.7.12
- `pip show connexion | grep "^Version\:"`: Version: 1.0.129

**Comment by hjacobs** [comment]
My evil (and not helpful) suggestion: switch to Python 3 :smirk:

**Comment by turdusmerula** [comment]
Planned but as long as 2.7 is the default version with ubuntu based distros I should keep going on figthing with 2.7 ;)

**Comment by jmcs** [comment]
The latest Ubuntu LTS (16.04) already has python 3 pre installed. If you mean `/usr/bin/python` being python 3 that will probably never happen because of [PEP 394](https://www.python.org/dev/peps/pep-0394/).

**Comment by etsardou** [comment]
A quick fix is to change the ```make_type``` function in ```connexion/decorators/parameter.py``` as so:

```
def make_type(value, type):
    type_func = TYPE_MAP[type]  # convert value to right type
    if type == 'string':
        if isinstance(value, str):
            return str(value)
        elif isinstance(value, unicode):
            return unicode(value)
    return type_func(value)
```
