### ISSUE TITLE
Connexion not returning a JSON response on `ExtraParameterProblem` exception

### ISSUE THREAD

**Issue by jasonrhaas** [zalando/connexion#574]
### Description
For some types of Connexion exceptions, the framework returns a JSON response, such as the below example when a parameter is missing for the **query** type.

```json
{
  "detail": "Wrong type, expected 'integer' for query parameter 'customer_id'",
  "status": 400,
  "title": "Bad Request",
  "type": "about:blank"
}
```

However, when a query parameter is incorrect, connexion returns a `ExtraParameterProblem` exception, and does a traceback.  This is not a very user friendly response.

### Expected behaviour
Return this to the API User:

```json
{
	"detail": "No such query parameter, 'foo'",
	"status": 422,
	"title": "Unprocessable Entity",
	"type": "about:blank"
}
```

### Actual behaviour

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/decorator.py", line 66, in wrapper
    response = function(request)
  File "/usr/local/lib/python3.6/site-packages/connexion/decorators/validation.py", line 267, in wrapper
    raise ExtraParameterProblem(formdata_errors, query_errors)
connexion.exceptions.ExtraParameterProblem: (set(), {'foo'})
```

### Steps to reproduce
Create a Swagger Schema that has something like the below example.  And then try to do a GET request like this:

GET
`/statements?customer_id=1&foo=1`

```yml
  /statements:
    get:
      tags:
      - developers
      summary: Gets a statement based on the customer and invoice id.
      x-swagger-router-controller: api.swagger
      operationId: Statements.get
      description: Gets a statement based on the customer id invoice id.  If the invoice id isn't provided, get them all.
      produces:
      - application/json
      parameters:
      - in: query
        name: customer_id
        description: pass in the unique customer id.
        required: true
        type: integer
        format: int32
      - in: query
        name: invoice_id
        description: pass in the unique invoice id.
        required: false
        type: integer
        format: int32
      responses:
        200:
          description: found invoice
          schema:
            $ref: '#/definitions/Statement'
        400:
          description: bad input parameter
        422:
          description: unprocessable entity
```

### Additional info:

Output of the commands:

- `python --version`
- `pip show connexion | grep "^Version\:"`

```
Python 3.6.2
Version: 1.1.16
```

**Comment by mohabusama** [comment]
@jasonrhaas I have tested with connexion 1.1.16 and 1.3 but couldn't reproduce the issue. 

Response:

```json
{
"detail": "Extra query parameter(s) foo not in spec",
"status": 400,
"title": null,
"type": "about:blank"
}
```

with ``strict_validation=True``

**Comment by jasonrhaas** [comment]
@mohabusama That's weird.  I also tried upgrading to 1.3 and get the same Exception.  It only happens when i have `strict_validation=True`.  What else could be causing this?  It seems like the error is happening before my implementation of `Statements.get`.

**Comment by jasonrhaas** [comment]
Also, not sure if it matters, but I'm using Swagger as a blueprint

```
class Swagger:

    def blueprint(spec, **yaml_kwargs):
        api = Api(spec, swagger_ui=False, strict_validation=True, validate_responses=False,
                  arguments=yaml_kwargs,
                  )
        bp = api.blueprint

        return bp
```

**Comment by mohabusama** [comment]
@jasonrhaas I think I found the issue. It is mainly related to error handling. I was able to fix it using the ``FlaskApp.common_error_handler``

Here is a working applications with a normal Flask app and Connexion Api blueprint:

```python
from flask import Flask
from connexion import Api, FlaskApp


class Swagger:
    def blueprint(spec, **yaml_kwargs):
        api = Api(spec, swagger_ui=False, strict_validation=True,
                  validate_responses=False, arguments=yaml_kwargs)
        bp = api.blueprint

        return bp


def query():
    return {'success': True}


if __name__ == '__main__':
    app = Flask(__name__)
    bp = Swagger.blueprint('swagger.yaml')

    app.register_blueprint(bp)
    app.register_error_handler(Exception, FlaskApp.common_error_handler)

    app.run(port=9090, debug=True)

```
``query`` is the configured endpoint.

**Comment by jasonrhaas** [comment]
@mohabusama That worked!  Is this something that should be fix in the Connexion base code somewhere or is this expected behavior (needing to add the `FlaskApp.common_error_handler`)

**Comment by mohabusama** [comment]
@jasonrhaas Connexion adds this error handler by default when you are using ``connexion.FlaskApp`` or ``connexion.App`` instead of using ``Flask()``. Connexion's FlaskApp is a wrapper around the normal Flask, so it adjusts all the required methods like the error handler.

If you go with ``connexion.App()`` instead of ``Flask()``, you can still get access to the raw flask application

```python
connexion_app = connexion.App(__name__)
connexion_app.add_api(...)

# this is Flask instance
assert isinstance(app.app, Flask) is True
```

**Comment by jasonrhaas** [comment]
OK, this is fixed... I'm now using the `connexion.App().app` for my Flask instance.  Thanks!
