### ISSUE TITLE
Python3 swagger.json generation error

### ISSUE THREAD

**Issue by merqurio** [zalando/connexion#63]
Hi ! I've been testing the generator and works perfectly on Python 2 but I get this error when asking for the swagger.json if I run it with python3. I'm not sure how I can help to get this working, but please let me know, I'll gladly help on this .

Thanks in advance

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.4/site-packages/connexion/api.py", line 141, in <lambda>
    self.blueprint.add_url_rule('/swagger.json', endpoint_name, lambda: flask.jsonify(self.specification))
  File "/usr/local/lib/python3.4/site-packages/flask/json.py", line 238, in jsonify
    indent=indent),
  File "/usr/local/lib/python3.4/site-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 194, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/encoder.py", line 345, in _iterencode_dict
    items = sorted(dct.items(), key=lambda kv: kv[0])
TypeError: unorderable types: str() < int()
```

**Comment by hjacobs** [comment]
Can you post your swagger.json? I believe you have somewhere a dictionary with both integer and string keys.

**Comment by hjacobs** [comment]
Most probably you can fix this by quoting the "integer" keys in your swagger.yaml (to make them strings).

**Comment by merqurio** [comment]
Thanks !
You were right. I should put everything in quotes ? Is this an exception ?

**Comment by hjacobs** [comment]
You don't need to put everything in quotes, but YAML will consider a sequence of digits as integers, i.e. this YAML will give you the above Python JSON serialization error (as it tries to sort the dictionary keys):

```yaml
---
mykey: foo
123: bar

**Comment by merqurio** [comment]
Understood ! Thanks a lot !!
