### ISSUE TITLE
Route annotations not working

### ISSUE THREAD

**Issue by Biskit1943** [zalando/connexion#721]
### Description
I wrote some wrapper for the routes to catch some general thinks like this:
```python
def validate(func):
    try:
        token = connexion.request.headers['Authorization']
    except KeyError:
        return "Unauthorized", 401

    @functools.wraps(func)
    def validated(*args, **kwargs):
        return func(*args, **kwargs)

    return validated
```
If I annotate my functions which I defined as `operationId` I get the an Runtime Error

### Expected behaviour
My routes are getting validated first

### Actual behaviour
```python
Failed to add operation for GET /apiv1/storage
Traceback (most recent call last):
  File "/home/storage/venv/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/storage/venv/lib/python3.7/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/home/storage/venv/lib/python3.7/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/storage/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/storage/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/storage/venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/storage/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/storage/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/storage/venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/storage/venv/lib/python3.7/site-packages/flask/cli.py", line 411, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
  File "/home/storage/venv/lib/python3.7/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/home/storage/venv/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/home/storage/storage.py", line 6, in <module>
    import app.database.administration as admin
  File "/home/storage/app/__init__.py", line 41, in <module>
    connexion_app.add_api('api.yml')
  File "/home/storage/venv/lib/python3.7/site-packages/connexion/apps/flask_app.py", line 54, in add_api
    api = super(FlaskApp, self).add_api(specification, **kwargs)
  File "/home/storage/venv/lib/python3.7/site-packages/connexion/apps/abstract.py", line 162, in add_api
    options=api_options.as_dict())
  File "/home/storage/venv/lib/python3.7/site-packages/connexion/apis/abstract.py", line 146, in __init__
    self.add_paths()
  File "/home/storage/venv/lib/python3.7/site-packages/connexion/apis/abstract.py", line 272, in add_paths
    self._handle_add_operation_error(path, method, sys.exc_info())
  File "/home/storage/venv/lib/python3.7/site-packages/connexion/apis/abstract.py", line 283, in _handle_add_operation_error
    six.reraise(*exc_info)
  File "/home/storage/venv/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/storage/venv/lib/python3.7/site-packages/connexion/apis/abstract.py", line 262, in add_paths
    self.add_operation(method, path, endpoint, path_parameters)
  File "/home/storage/venv/lib/python3.7/site-packages/connexion/apis/abstract.py", line 215, in add_operation
    pass_context_arg_name=self.pass_context_arg_name)
  File "/home/storage/venv/lib/python3.7/site-packages/connexion/operation.py", line 228, in __init__
    resolution = resolver.resolve(self)
  File "/home/storage/venv/lib/python3.7/site-packages/connexion/resolver.py", line 40, in resolve
    return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
  File "/home/storage/venv/lib/python3.7/site-packages/connexion/resolver.py", line 62, in resolve_function_from_operation_id
    return self.function_resolver(operation_id)
  File "/home/storage/venv/lib/python3.7/site-packages/connexion/utils.py", line 36, in get_function_from_name
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/storage/app/api/routes.py", line 17, in <module>
    @_user_validation
  File "/home/storage/app/api/wrapper.py", line 21, in _user_validation
    token = connexion.request.headers['Authorization']
  File "/home/storage/venv/lib/python3.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/storage/venv/lib/python3.7/site-packages/werkzeug/local.py", line 306, in _get_current_object
    return self.__local()
  File "/home/storage/venv/lib/python3.7/site-packages/flask/globals.py", line 37, in _lookup_req_object
    raise RuntimeError(_request_ctx_err_msg)
RuntimeError: Working outside of request context.

This typically means that you attempted to use functionality that needed
an active HTTP request.  Consult the documentation on testing for
information about how to avoid this problem.
```

### Steps to reproduce
Annotate a route with a self written function

Output of the commands:

- `python --version` => `Python 3.7.0`
- `pip show connexion | grep "^Version\:"` => `Version: 1.5.3`

**Comment by Biskit1943** [comment]
So, I found the Issue. I've annotated the function wrong. I looked around a bit and found the solution in the [examples](https://github.com/zalando/connexion/tree/master/examples/basicauth). Here is my new wrapper function

```python
from decorator import decorator  # pip install decorator

@decorator
def validate(func, *args, **kwargs):
    try:
        token = connexion.request.headers['Authorization']
    except KeyError:
        return "Unauthorized", 401

    return func(*args, **kwargs)
```
