### ISSUE TITLE
There is no `get_tokeninfo_url` function in `security` module

### ISSUE THREAD

**Issue by fwkz** [zalando/connexion#752]
### Description
There is no `get_tokeninfo_url` function in `security` module.
```
>>> from connexion import operation
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mkupidura/.virtualenvs/req-up/lib/python3.7/site-packages/connexion/operation.py", line 11, in <module>
    from .decorators.security import (get_tokeninfo_func, get_tokeninfo_url,
ImportError: cannot import name 'get_tokeninfo_url' from 'connexion.decorators.security' (/Users/mkupidura/.virtualenvs/req-up/lib/python3.7/site-packages/connexion/decorators/security.py)
```

Looking at the `security.get_tokeninfo_func` doc-string it might be some refactoring left-overs
```python
def get_tokeninfo_func(security_definition):
    """
    :type security_definition: dict
    :rtype: function

    >>> get_tokeninfo_url({'x-tokenInfoFunc': 'foo.bar'})
    '<function foo.bar>'
    """
    # ...
```

### Additional info:

Output of the commands:

- `Python 3.7.0`
- `Version: 2.0.0`

**Comment by dtkav** [comment]
Hi @fwkz - can you make sure you clean out all of your .pyc files?

The `operation` class was split out into two distinct classes to support swagger 2.x and openapi 3.x.x simultaneously, so you cannot `from connexion import operation` anymore.
`from connexion.operations import (SecureOperation, Swagger2Operation, OpenAPIOperation)` should work though.

If you can say more about what you're trying to do, I might be able to help more.

**Comment by nabrowning** [comment]
Hi @dtkav -
I am also having the same issue as @fwkz 
I re-cloned my repo that I am working on today and re `pip install`ed all of my requirements.

I am getting this stack trace
```
  File "/home/natalie/code/eeg-web-interface/applications/modules/eegcloud_apis/eegcloud_apis/applications/modules/connexion_utils.py", line 12, in <module>
    from connexion.operation import security_passthrough
  File "/home/natalie/code/eeg-web-interface/venv/local/lib/python2.7/site-packages/connexion/operation.py", line 11, in <module>
    from .decorators.security import (get_tokeninfo_func, get_tokeninfo_url,
ImportError: cannot import name get_tokeninfo_url
```
The issue starts in my code where I call this:
```
from connexion.operation import security_passthrough
```
I took a look at `operation.py` and found this code at `line 11`
```
from .decorators.security import (get_tokeninfo_func, get_tokeninfo_url,
                                  security_passthrough, verify_oauth_local,
                                  verify_oauth_remote)
```
and yet, when I go to `.decorators.security` I see this:
```
def get_tokeninfo_func(security_definition):
    """
    :type security_definition: dict
    :rtype: function

    >>> get_tokeninfo_url({'x-tokenInfoFunc': 'foo.bar'})
    '<function foo.bar>'
    """
    token_info_func = (security_definition.get("x-tokenInfoFunc") or
                       os.environ.get('TOKENINFO_FUNC'))
    if token_info_func:
        return get_function_from_name(token_info_func)

    token_info_url = (security_definition.get('x-tokenInfoUrl') or
                      os.environ.get('TOKENINFO_URL'))
    if token_info_url:
        return functools.partial(get_tokeninfo_remote, token_info_url)

    return None


def get_scope_validate_func(security_definition):
    """
    :type security_definition: dict
    :rtype: function

    >>> get_scope_validate_func({'x-scopeValidateFunc': 'foo.bar'})
    '<function foo.bar>'
    """
    func = (security_definition.get("x-scopeValidateFunc") or
            os.environ.get('SCOPEVALIDATE_FUNC'))
    if func:
        return get_function_from_name(func)
    return validate_scope
```
I then went over to my coworker who did not re `pip install` her requirements yet today, and saw this code in `.decorators.security`:
```
def get_tokeninfo_func(security_definition):
    """
    :type security_definition: dict
    :rtype: function

    >>> get_tokeninfo_url({'x-tokenInfoFunc': 'foo.bar>'})
    '<function foo.bar>'
    """
    token_info_func = (security_definition.get("x-tokenInfoFunc") or
                       os.environ.get('TOKENINFO_FUNC'))
    return get_function_from_name(token_info_func) if token_info_func else None


def get_tokeninfo_url(security_definition):
    """
    :type security_definition: dict
    :rtype: str

    >>> get_tokeninfo_url({'x-tokenInfoUrl': 'foo'})
    'foo'
    """
    token_info_url = (security_definition.get('x-tokenInfoUrl') or
                      os.environ.get('TOKENINFO_URL'))
    return token_info_url


def security_passthrough(function):
    """
    :type function: types.FunctionType
    :rtype: types.FunctionType
    """
    return function


def get_authorization_token(request):
    authorization = request.headers.get('Authorization')  # type: str
    if not authorization:
        logger.info("... No auth provided. Aborting with 401.")
        raise OAuthProblem(description='No authorization token provided')
    else:
        try:
            _, token = authorization.split()  # type: str, str
        except ValueError:
            raise OAuthProblem(description='Invalid authorization header')
    return token
```
so clearly there is a discrepancy here. the `operation.py` file is expecting a method called `get_token_url` to exist in `.decorators.security.py` and yet it doesn't exist. it did, however, exist yesterday. So that is a little worrisome

Let me know if this is a bug or if I am doing something incorrectly.

**Comment by dtkav** [comment]
Hi @nabrowning - `operation.py` no longer exists, so cannot be imported. This was intended to be backwards compatible, but it must have gotten lost somewhere along the way.

Here's what happens when I try to import connexion.operation (and why I think you may have a .pyc file somewhere):
```
(venv) connexion/connexion content_type_validation > ipython
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from connexion.operation import security_passthrough
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-7b0f5d377fd6> in <module>()
----> 1 from connexion.operation import security_passthrough

ModuleNotFoundError: No module named 'connexion.operation'
```
And here's me importing security_passthrough from its new home in 2.0:
```
In [2]: from connexion.operations.secure import security_passthrough

In [3]: security_passthrough
Out[3]: <function connexion.decorators.security.security_passthrough(function)>
```
Connexion 2.0 has some backwards-incompatible changes, so you have two options:
1. Pin your connexion to 1.5.3
2. Update your code to use Connexion 2.0 like this:
```
from connexion.operations.secure import security_passthrough
```

I'll also put up a PR to make `connexion.operation` into a dummy module that links to `* from secure, swagger2`, so hopefully this won't be a surprise to future folks in 2.0.2

Let me know if either of those options work for you.

**Comment by fwkz** [comment]
Brand new virtualenv seems to have `operation` module 🤔 
```
~/.virtualenvs/conn/lib/python3.6/site-packages/connexion $ ls -la | grep operation
-rw-r--r--   1 fwkz  staff  19198  7 lis 23:51 operation.py
drwxr-xr-x   8 fwkz  staff    256  7 lis 23:51 operations
```

**Comment by dtkav** [comment]
@fwkz you're right! That's spooky! :ghost:

My guess is that the build/release process doesn't clean up deleted files properly.
That file is definitely not tracked in git.

 @jmcs any ideas what happened?

**Comment by dtkav** [comment]
@fwkz the next release of connexion (2.0.2) will include a proxy `operation` class for backwards compatibility. If you like, you can try it out by installing from a commit on master:
`pip install git+git://github.com/zalando/connexion.git@343643428cf68b9c4bfba21fe3df162170c68b48`

**Comment by fwkz** [comment]
@dtkav Really appreciate the effort. 🤗
