### ISSUE TITLE
URL for UI must have ui/

### ISSUE THREAD

**Issue by ericraymond** [zalando/connexion#831]
### Description

In 2.1, the url for the ui must have a slash after ui (e.g., https://site.name/ui/)  Request to https://site.name/ui fail

### Expected behaviour

https://site.name/ui should work the same as https://site.name/ui/

### Actual behaviour

Throws a 500 error with the following logs:

```ERROR:root:----- Server Exception -----
Error: 301 Moved Permanently: None
Traceback:
Traceback (most recent call last):
  File "/home/ubuntu/foo/site-packages/werkzeug/routing.py", line 1538, in match
    rv = rule.match(path, method)
  File "/home/ubuntu/foo/site-packages/werkzeug/routing.py", line 776, in match
    raise RequestSlash()
werkzeug.routing.RequestSlash
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/ubuntu/foo/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/foo/site-packages/flask/app.py", line 1791, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/ubuntu/foo/site-packages/flask/app.py", line 1774, in raise_routing_exception
    raise request.routing_exception
  File "/home/ubuntu/foo/site-packages/flask/ctx.py", line 336, in match_request
    self.url_adapter.match(return_rule=True)
  File "/home/ubuntu/foo/site-packages/werkzeug/routing.py", line 1542, in match
    safe='/:|+') + '/', query_args))
werkzeug.routing.RequestRedirect: 301 Moved Permanently: None```


### Steps to reproduce

Using swagger (openapi 2) definition in connexion.

Visit https://site.name/ui

### Additional info:

Output of the commands:

Python 3.6.5 :: Anaconda, Inc.

connexion 2.1.0

**Comment by dtkav** [comment]
I wasn't able to reproduce this with Flask, but I think it is an issue with aiohttp.
There's an open PR to fix this issue here: #827
