### ISSUE TITLE
swagger-ui incompatible with latest openapi-spec-validator? pyaml collision?

### ISSUE THREAD

**Issue by tommyjcarpenter** [zalando/connexion#950]
### Description
This just broke between last Friday and today. It looks like validator just had a commit 6 hours ago, though it's not apparent to me what the problem is here. 

My package (called `a1`) depends on `requests, Flask, gevent, connexion[swagger-ui], jsonschema`. I do not specify any versions of these in my setup. 

It looks like spec validator: https://github.com/p1c2u/openapi-spec-validator/blob/master/setup.py#L72
wants PyYaml > 5.1

It looks like connexion https://github.com/zalando/connexion/blob/master/setup.py#L26
also wants 5.1

requests, flask, gevent, jsonschema do not appear to depend on pyyaml

```
Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (from a1==0.6.0) (2.21.0)
Requirement already satisfied: Flask in /usr/lib/python3.7/site-packages (from a1==0.6.0) (1.0.3)
Requirement already satisfied: connexion[swagger-ui] in /usr/lib/python3.7/site-packages (from a1==0.6.0) (2.2.0)
Requirement already satisfied: gevent in /usr/lib/python3.7/site-packages (from a1==0.6.0) (1.4.0)
Requirement already satisfied: rmr in /usr/lib/python3.7/site-packages (from a1==0.6.0) (0.10.1)
Requirement already satisfied: jsonschema in /usr/lib/python3.7/site-packages (from a1==0.6.0) (2.6.0)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.7/site-packages (from requests->a1==0.6.0) (3.0.4)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.7/site-packages (from requests->a1==0.6.0) (2.8)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.7/site-packages (from requests->a1==0.6.0) (1.24.2)
Requirement already satisfied: itsdangerous>=0.24 in /usr/lib/python3.7/site-packages (from Flask->a1==0.6.0) (1.1.0)
Requirement already satisfied: click>=5.1 in /usr/lib/python3.7/site-packages (from Flask->a1==0.6.0) (7.0)
Requirement already satisfied: Werkzeug>=0.14 in /usr/lib/python3.7/site-packages (from Flask->a1==0.6.0) (0.15.4)
Requirement already satisfied: Jinja2>=2.10 in /usr/lib/python3.7/site-packages (from Flask->a1==0.6.0) (2.10.1)
Requirement already satisfied: clickclick>=1.2 in /usr/lib/python3.7/site-packages (from connexion[swagger-ui]->a1==0.6.0) (1.2.2)
Requirement already satisfied: inflection>=0.3.1 in /usr/lib/python3.7/site-packages (from connexion[swagger-ui]->a1==0.6.0) (0.3.1)
Requirement already satisfied: PyYAML>=3.13 in /usr/lib/python3.7/site-packages (from connexion[swagger-ui]->a1==0.6.0) (3.13)
Requirement already satisfied: openapi-spec-validator>=0.2.4 in /usr/lib/python3.7/site-packages (from connexion[swagger-ui]->a1==0.6.0) (0.2.7)
Requirement already satisfied: six>=1.9 in /usr/lib/python3.7/site-packages (from connexion[swagger-ui]->a1==0.6.0) (1.12.0)
Requirement already satisfied: swagger-ui-bundle>=0.0.2; extra == "swagger-ui" in /usr/lib/python3.7/site-packages (from connexion[swagger-ui]->a1==0.6.0) (0.0.3)
Requirement already satisfied: greenlet>=0.4.14; platform_python_implementation == "CPython" in /usr/lib/python3.7/site-packages (from gevent->a1==0.6.0) (0.4.15)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3.7/site-packages (from Jinja2>=2.10->Flask->a1==0.6.0) (1.1.1)
Installing collected packages: a1
  Found existing installation: a1 0.6.0
    Uninstalling a1-0.6.0:
      Successfully uninstalled a1-0.6.0
  Running setup.py develop for a1
Successfully installed a1
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyYAML 3.13 (/usr/lib/python3.7/site-packages), Requirement.parse('PyYAML>=5.1'), {'openapi-spec-validator'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/run.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyYAML 3.13 (/usr/lib/python3.7/site-packages), Requirement.parse('PyYAML>=5.1'), {'openapi-spec-validator'})
```

### Additional info:

Output of the commands:

- `python --version`
```
Python 3.7.3
```
- `pip show connexion | grep "^Version\:"`
```
Version: 2.2.0
```

**Comment by tommyjcarpenter** [comment]
I think this was caused because PyYAML cannot be simply pip uninstalled. I had to force the removal of the old package.
